function loadSettings(){try{return {...{currency:'EUR',defaultMethod:'Girokonto'},...JSON.parse(localStorage.getItem('moneybrain.settings'))}}catch{return {currency:'EUR',defaultMethod:'Girokonto'}}}
let settings=loadSettings();
let euro = new Intl.NumberFormat('de-DE',{style:'currency',currency:settings.currency});
const monthFmt = new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'});
const shortDate = new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'short'});
const now = new Date();
const legacySeedIds=new Set(['1','2','3','4','5','6']);
function cleanStoredTransactions(items){return Array.isArray(items)?items.filter(item=>!legacySeedIds.has(String(item?.id))).map(item=>String(item?.source||'').includes('PayPal-Nachweis')?{...item,name:cleanStoredPayPalName(item.name)}:item):[]}
function cleanStoredPayPalName(value){let name=String(value||'PayPal').replace(/^[=+\-−–|:;.,_\s]+/,'').replace(/^MT\s+(?=Monika)/i,'').trim();if(/z{1,2}[o0]{2}\s*sky\s*24/i.test(name))return 'zooSky24';return name}
function load(){try{return cleanStoredTransactions(JSON.parse(localStorage.getItem('moneybrain.transactions')))}catch{return []}}
let state={route:'home',filter:'all',archiveMode:'month',archiveDate:new Date(),statsYear:new Date().getFullYear(),transactions:load()};
function save(){
 state.transactions=reconcileAllTransactions(state.transactions);
 const snapshot=cleanStoredTransactions(state.transactions);state.transactions=snapshot;
 localStorage.setItem('moneybrain.localUpdatedAt',new Date().toISOString());
 try{localStorage.setItem('moneybrain.transactions',JSON.stringify(snapshot))}catch{}
 backupTransactions(snapshot);
 window.MoneybrainCloud?.queueUpload(snapshot);
}
function openMoneybrainDataDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open('moneybrain-data',1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('state'))request.result.createObjectStore('state',{keyPath:'key'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function backupTransactions(items){try{const db=await openMoneybrainDataDb();await new Promise((resolve,reject)=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put({key:'transactions',items:cleanStoredTransactions(items),updatedAt:new Date().toISOString()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}catch{}}
async function readTransactionBackup(){try{const db=await openMoneybrainDataDb(),value=await new Promise((resolve,reject)=>{const tx=db.transaction('state','readonly'),request=tx.objectStore('state').get('transactions');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();return cleanStoredTransactions(value?.items)}catch{return []}}
async function restorePersistentTransactions(){
 try{await navigator.storage?.persist?.()}catch{}
 const backup=await readTransactionBackup();
 const byId=new Map();for(const item of backup)byId.set(String(item.id),item);for(const item of state.transactions)byId.set(String(item.id),item);
 const restored=cleanStoredTransactions([...byId.values()]);
 if(restored.length){const recovered=restored.length>state.transactions.length;state.transactions=restored;try{localStorage.setItem('moneybrain.transactions',JSON.stringify(restored))}catch{}backupTransactions(restored);if(recovered){render();showToast('Gespeicherte Buchungen wiederhergestellt')}}
}

const app=document.querySelector('#app'),sheet=document.querySelector('#sheet'),content=document.querySelector('#sheetContent');
const inMonth=(t,d=now)=>{const x=new Date(t.date);return x.getMonth()===d.getMonth()&&x.getFullYear()===d.getFullYear()};
const txs=(date=now)=>state.transactions.filter(t=>inMonth(t,date)).sort((a,b)=>new Date(b.date)-new Date(a.date));
const total=(items,type)=>items.reduce((sum,item)=>sum+(window.MoneybrainMovements?.economicAmount(item,type)??(item.type===type&&!item.amountUncertain?Number(item.amount):0)),0);
function monthToDateComparison(type){
 const day=now.getDate(),previous=new Date(now.getFullYear(),now.getMonth()-1,1),lastPreviousDay=new Date(previous.getFullYear(),previous.getMonth()+1,0).getDate(),through=Math.min(day,lastPreviousDay);
 const previousItems=state.transactions.filter(t=>{const d=new Date(t.date);return d.getFullYear()===previous.getFullYear()&&d.getMonth()===previous.getMonth()&&d.getDate()<=through});
 const difference=total(txs(),type)-total(previousItems,type),sign=difference>0?'+':difference<0?'−':'±',tone=type==='income'?(difference>=0?'good':'bad'):(difference<=0?'good':'bad');
 const month=new Intl.DateTimeFormat('de-DE',{month:'long'}).format(previous);
 return `<small class="comparison ${tone}">${sign}${euro.format(Math.abs(difference))} · 1.–${through}. ${month}</small>`;
}
function render(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));if(state.route==='home')home();if(state.route==='transactions')transactions();if(state.route==='money')money();if(state.route==='statistics')statistics();if(state.route==='archive')archive()}
function home(){const m=txs(),inc=total(m,'income'),exp=total(m,'expense');app.innerHTML=`
 <section class="hero"><h1><span class="hero-name">moneybrain</span><span class="hero-tagline">Deine Finanzen.<br>Alles im Blick.</span></h1></section>
 <div class="month-row"><h2>${capitalize(monthFmt.format(now))}</h2><span class="month-chip">Heute, ${now.getDate()}.</span></div>
 <div class="balance-grid">
  <button class="balance-card income" data-open-type="income"><span class="card-icon">↙</span><span class="card-label">Einnahmen</span><span class="amount">${euro.format(inc)}</span>${monthToDateComparison('income')}</button>
  <button class="balance-card expense" data-open-type="expense"><span class="card-icon">↗</span><span class="card-label">Ausgaben</span><span class="amount">${euro.format(exp)}</span>${monthToDateComparison('expense')}</button>
 </div>
 <button class="primary" id="newTx"><span>＋</span> Neue Buchung</button>
 <div class="section-title"><h2>Letzte Buchungen</h2><button class="link-button" data-go="transactions">Alle ansehen</button></div>
 ${list(m.slice(0,4))}`;bindCommon();document.querySelector('#newTx').onclick=openNew;document.querySelectorAll('[data-open-type]').forEach(b=>b.onclick=()=>{state.route='transactions';state.filter=b.dataset.openType;render()})}
function transactions(){let m=txs();if(state.filter!=='all')m=m.filter(x=>x.type===state.filter);app.innerHTML=`<div class="page-head"><div><span class="eyebrow">Aktueller Monat</span><h1>Buchungen</h1><p class="subtitle">${m.length} Transaktionen</p></div><button class="icon-button" id="addSmall">＋</button></div>
 <div class="filter-row">${[['all','Alle'],['income','Einnahmen'],['expense','Ausgaben'],['review','Zu prüfen']].map(([v,l])=>`<button class="filter ${state.filter===v?'active':''}" data-filter="${v}">${l}</button>`).join('')}</div>${list(m)}`;document.querySelector('#addSmall').onclick=openNew;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;if(state.filter==='review'){m=txs().filter(x=>x.status==='review');app.querySelector('.transaction-list')?.remove();app.insertAdjacentHTML('beforeend',list(m))}else render();bindTransactions()});bindTransactions()}
function money(){
 const accounts=window.MoneybrainAccounts,summary=accounts.totals(state.transactions),budget=summary.rows.filter(account=>account.includeInBudget),assets=summary.rows.filter(account=>!account.includeInBudget),unassigned=accounts.unassigned(state.transactions);
 const rows=items=>items.length?`<div class="money-account-list">${items.map(account=>`<button class="money-account" data-account-id="${account.id}"><span class="money-account-icon">${accountTypeIcon(account.type)}</span><span><strong>${escapeHtml(account.name)}</strong><small>${account.active?'Aktiv':'Inaktiv'} · ${account.includeInBudget?'Alltagsbudget':'Vermögen'}</small></span><b>${euro.format(account.balance)}</b></button>`).join('')}</div>`:'<div class="empty money-empty">Noch kein Geldtopf in diesem Bereich.</div>';
 app.innerHTML=`<div class="page-head money-head"><div><span class="eyebrow">Deine Geldtöpfe</span><h1>Geld</h1><p class="subtitle">Wo dein Geld liegt und was im Alltag zählt</p></div><button class="icon-button" id="addAccountSmall">＋</button></div>
  <section class="money-total"><span class="eyebrow">Verfügbares Geld</span><strong>${euro.format(summary.available)}</strong><small>Aus allen aktiven Geldtöpfen im Alltagsbudget</small></section>
  ${unassigned?`<div class="review-box money-warning"><strong>${unassigned} historische Buchung${unassigned===1?'':'en'} ohne Geldtopf</strong><p>Diese V1-Buchungen bleiben bewusst unverändert und wirken nicht auf die neuen Salden.</p></div>`:''}
  <div class="section-title"><h2>Alltagsgeld</h2><span class="money-subtotal">${euro.format(summary.available)}</span></div>${rows(budget)}
  <div class="section-title money-assets-title"><div><span class="eyebrow">Getrennt betrachtet</span><h2>Ersparnisse & Vermögen</h2></div><span class="money-subtotal">${euro.format(summary.assets)}</span></div>${rows(assets)}
  <div class="money-actions"><button class="primary" id="reconcileAll"><span>✓</span> Salden abgleichen</button><button class="primary" id="newTransfer"><span>↔</span> Transfer</button><button class="primary" id="addAccount"><span>＋</span> Geldtopf</button></div>`;
 document.querySelector('#reconcileAll').onclick=openBalanceOverview;document.querySelector('#newTransfer').onclick=openTransferForm;document.querySelector('#addAccount').onclick=()=>openAccountForm();document.querySelector('#addAccountSmall').onclick=()=>openAccountForm();document.querySelectorAll('[data-account-id]').forEach(button=>button.onclick=()=>openAccountForm(accounts.all().find(account=>account.id===button.dataset.accountId)));
}
function accountTypeIcon(type){return ({bank:'▣',paypal:'P',cash:'◉',savings:'◇',investment:'↗',other:'•'})[type]||'•'}
function openAccountForm(existing){
 const accounts=window.MoneybrainAccounts,account=existing||{name:'',type:'bank',active:true,includeInBudget:true},history=existing?accounts.history(existing.id):[],calculated=existing?accounts.balance(existing,state.transactions):0,canDelete=existing&&!accounts.hasHistory(existing.id,state.transactions);
 const historyHtml=history.length?`<div class="reconciliation-history"><span class="eyebrow">Salden-Historie</span>${history.map(item=>`<div class="reconciliation-entry"><div><strong>${new Date(item.reconciledAt).toLocaleString('de-DE')}</strong><small>Berechnet ${euro.format(item.calculatedBalance)} · Tatsächlich ${euro.format(item.actualBalance)}</small></div><b class="${item.difference>=0?'positive':'negative'}">${item.difference>=0?'+':''}${euro.format(item.difference)}</b></div>`).join('')}</div>`:'';
 open(`<div class="sheet-title"><h2>${existing?'Geldtopf bearbeiten':'Neuer Geldtopf'}</h2><button class="close">✕</button></div>${existing?`<section class="account-balance-card"><span>Berechneter Saldo</span><strong>${euro.format(calculated)}</strong><button class="secondary" type="button" id="reconcileAccount">Saldo abgleichen</button></section>`:''}<form class="form" id="accountForm"><div class="field"><label>Name</label><input name="name" value="${escapeHtml(account.name)}" maxlength="80" required placeholder="z. B. Tagesgeld"></div><div class="field"><label>Typ</label><select name="type">${accounts.types.map(([value,label])=>`<option value="${value}" ${account.type===value?'selected':''}>${label}</option>`).join('')}</select></div><label class="toggle-row"><input name="includeInBudget" type="checkbox" ${account.includeInBudget?'checked':''}><span><strong>Im Alltagsbudget berücksichtigen</strong><small>Spar- und Anlagetöpfe normalerweise deaktivieren.</small></span></label><label class="toggle-row"><input name="active" type="checkbox" ${account.active?'checked':''}><span><strong>Geldtopf aktiv</strong><small>Geldtöpfe mit Historie können deaktiviert, aber nicht gelöscht werden.</small></span></label><button class="primary" type="submit">${existing?'Änderungen speichern':'Geldtopf anlegen'}</button></form>${historyHtml}${canDelete?'<button class="secondary danger account-delete" id="deleteAccount">Unbenutzten Geldtopf löschen</button>':''}`);
 const form=content.querySelector('#accountForm'),type=form.querySelector('[name="type"]'),budget=form.querySelector('[name="includeInBudget"]');
 if(!existing)type.onchange=()=>{budget.checked=!['savings','investment'].includes(type.value)};
 form.onsubmit=event=>{event.preventDefault();const data=new FormData(form),payload={name:String(data.get('name')).trim(),type:String(data.get('type')),includeInBudget:Boolean(data.get('includeInBudget')),active:Boolean(data.get('active'))};if(existing)accounts.update(existing.id,payload);else accounts.create(payload);sheet.close();state.route='money';render();showToast(existing?'Geldtopf aktualisiert':'Geldtopf angelegt')};
 content.querySelector('#reconcileAccount')?.addEventListener('click',()=>openReconciliation(existing));
 content.querySelector('#deleteAccount')?.addEventListener('click',()=>{if(confirm('Diesen unbenutzten Geldtopf wirklich löschen?')){accounts.remove(existing.id,state.transactions);sheet.close();state.route='money';render();showToast('Geldtopf gelöscht')}});
}
function localDateTimeValue(date=new Date()){const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16)}
function openReconciliation(account){
 const accounts=window.MoneybrainAccounts;
 open(`<div class="sheet-title"><h2>Saldo abgleichen</h2><button class="close">✕</button></div><p class="subtitle">${escapeHtml(account.name)} · der Abgleich wird dauerhaft in der Historie gespeichert.</p><form class="form" id="reconciliationForm"><div class="field"><label>Stichtag</label><input name="reconciledAt" type="datetime-local" value="${localDateTimeValue()}" required></div><div class="reconciliation-preview"><div><span>Berechnet</span><strong id="calculatedBalance">${euro.format(accounts.balance(account,state.transactions))}</strong></div><div><span>Tatsächlich</span><strong id="actualBalance">—</strong></div><div><span>Differenz</span><strong id="balanceDifference">—</strong></div></div><div class="field"><label>Tatsächlicher Saldo</label><input name="actualBalance" type="number" step="0.01" required placeholder="0,00"></div><div class="field"><label>Optionale Notiz</label><textarea name="note" placeholder="z. B. PayPal-Saldo manuell geprüft"></textarea></div><button class="secondary" id="addMissingBooking" type="button">Fehlende Buchung nachtragen</button><button class="primary" type="submit">Saldo korrigieren</button></form>`);
 const form=content.querySelector('#reconciliationForm'),actualInput=form.querySelector('[name="actualBalance"]'),dateInput=form.querySelector('[name="reconciledAt"]');
 const refresh=()=>{const at=new Date(dateInput.value).toISOString(),calculated=accounts.balanceAt(account,state.transactions,at),actual=actualInput.value===''?null:Number(actualInput.value),difference=actual===null?null:Math.round((actual-calculated+Number.EPSILON)*100)/100;content.querySelector('#calculatedBalance').textContent=euro.format(calculated);content.querySelector('#actualBalance').textContent=actual===null?'—':euro.format(actual);const differenceElement=content.querySelector('#balanceDifference');differenceElement.textContent=difference===null?'—':`${difference>=0?'+':''}${euro.format(difference)}`;differenceElement.className=difference===null?'':difference>=0?'positive':'negative'};
 actualInput.oninput=refresh;dateInput.onchange=refresh;
 content.querySelector('#addMissingBooking').onclick=()=>manualForm(null,{accountId:account.id,date:String(dateInput.value).slice(0,10),note:'Nach Saldenabgleich nachgetragen'});
 form.onsubmit=event=>{event.preventDefault();const data=new FormData(form),at=new Date(String(data.get('reconciledAt'))).toISOString();accounts.reconcile(account.id,Number(data.get('actualBalance')),at,state.transactions,String(data.get('note')||''));sheet.close();state.route='money';render();showToast('Saldo-Korrektur gespeichert')};
}
function openBalanceOverview(){
 const accountsApi=window.MoneybrainAccounts,items=accountsApi.active();if(!items.length){showToast('Keine aktiven Geldtöpfe vorhanden');return}
 open(`<div class="sheet-title"><h2>Salden abgleichen</h2><button class="close">✕</button></div><p class="subtitle">Nur ausgefüllte Geldtöpfe werden korrigiert. Leere Felder verändern nichts.</p><form class="form" id="balanceOverviewForm"><div class="field"><label>Gemeinsamer Stichtag</label><input name="reconciledAt" type="datetime-local" value="${localDateTimeValue()}" required></div><div id="balanceOverviewRows">${items.map(account=>`<section class="balance-overview-row" data-account-id="${account.id}"><div><strong>${escapeHtml(account.name)}</strong><small>Berechnet: <b data-calculated>${euro.format(accountsApi.balance(account,state.transactions))}</b></small></div><div class="field"><label>Tatsächlich (optional)</label><input name="actual-${account.id}" type="number" step="0.01" placeholder="Nicht abgleichen"></div><small class="balance-overview-difference" data-difference>Keine Eingabe</small><button class="secondary" type="button" data-missing="${account.id}">Fehlende Buchung</button></section>`).join('')}</div><button class="primary" id="saveBalanceOverview" type="submit" disabled>Ausgefüllte Salden korrigieren</button></form>`);
 const form=content.querySelector('#balanceOverviewForm'),dateInput=form.querySelector('[name="reconciledAt"]'),saveButton=content.querySelector('#saveBalanceOverview');
 const refresh=()=>{const at=new Date(dateInput.value).toISOString();let filled=0;content.querySelectorAll('.balance-overview-row').forEach(row=>{const account=items.find(item=>item.id===row.dataset.accountId),calculated=accountsApi.balanceAt(account,state.transactions,at),input=row.querySelector('input'),difference=row.querySelector('[data-difference]');row.querySelector('[data-calculated]').textContent=euro.format(calculated);if(input.value===''){difference.textContent='Keine Eingabe';difference.className='balance-overview-difference';return}filled++;const delta=Math.round((Number(input.value)-calculated+Number.EPSILON)*100)/100;difference.textContent=`Differenz: ${delta>=0?'+':''}${euro.format(delta)}`;difference.className=`balance-overview-difference ${delta>=0?'positive':'negative'}`});saveButton.disabled=!filled};
 form.querySelectorAll('input[type="number"]').forEach(input=>input.oninput=refresh);dateInput.onchange=refresh;content.querySelectorAll('[data-missing]').forEach(button=>button.onclick=()=>manualForm(null,{accountId:button.dataset.missing,date:String(dateInput.value).slice(0,10),note:'Nach Saldenabgleich nachgetragen'}));
 form.onsubmit=event=>{event.preventDefault();const at=new Date(dateInput.value).toISOString(),filled=items.filter(account=>form.querySelector(`[name="actual-${account.id}"]`).value!=='');filled.forEach(account=>accountsApi.reconcile(account.id,Number(form.querySelector(`[name="actual-${account.id}"]`).value),at,state.transactions,'Zentraler Saldenabgleich'));sheet.close();state.route='money';render();showToast(`${filled.length} Saldo-Korrektur${filled.length===1?'':'en'} gespeichert`)};
 refresh();
}
function openTransferForm(){
 const accounts=window.MoneybrainAccounts.active();if(accounts.length<2){showToast('Für einen Transfer werden zwei aktive Geldtöpfe benötigt');return}
 const options=selected=>accounts.map(account=>`<option value="${account.id}" ${selected===account.id?'selected':''}>${escapeHtml(account.name)}</option>`).join('');
 open(`<div class="sheet-title"><h2>Transfer</h2><button class="close">✕</button></div><p class="subtitle">Verschiebt Geld zwischen eigenen Geldtöpfen – keine Einnahme und keine Ausgabe.</p><form class="form" id="transferForm"><div class="field"><label>Von</label><select name="sourceAccountId" required>${options(accounts[0].id)}</select></div><div class="field"><label>Nach</label><select name="targetAccountId" required>${options(accounts[1].id)}</select></div><div class="field"><label>Betrag</label><input name="amount" type="number" min="0.01" step="0.01" required></div><div class="field"><label>Datum</label><input name="occurredAt" type="datetime-local" value="${localDateTimeValue()}" required></div><div class="field"><label>Optionale Notiz</label><textarea name="note" placeholder="z. B. Bargeld abgehoben"></textarea></div><button class="primary" type="submit">Transfer speichern</button></form>`);
 const form=content.querySelector('#transferForm');form.onsubmit=event=>{event.preventDefault();try{const data=new FormData(form);window.MoneybrainMovements.createTransfer({sourceAccountId:String(data.get('sourceAccountId')),targetAccountId:String(data.get('targetAccountId')),amount:Number(data.get('amount')),occurredAt:new Date(String(data.get('occurredAt'))).toISOString(),note:String(data.get('note')||'')});sheet.close();state.route='money';render();showToast('Transfer gespeichert')}catch(error){showToast(error.message)}};
}
function archive(){const d=state.archiveDate;const year=d.getFullYear(),allYear=state.transactions.filter(t=>new Date(t.date).getFullYear()===year).sort((a,b)=>new Date(b.date)-new Date(a.date));const shown=state.archiveMode==='year'?allYear:txs(d);app.innerHTML=`<div class="page-head"><div><span class="eyebrow">Gespeicherte Daten</span><h1>Archiv</h1><p class="subtitle">Monate und Jahre vergleichen</p></div></div>
 <div class="filter-row"><button class="filter ${state.archiveMode==='month'?'active':''}" data-mode="month">Monat</button><button class="filter ${state.archiveMode==='year'?'active':''}" data-mode="year">Ganzes Jahr</button></div>
 <div class="month-row"><button class="month-chip" data-step="-1">‹</button><h2>${state.archiveMode==='year'?year:capitalize(monthFmt.format(d))}</h2><button class="month-chip" data-step="1">›</button></div>
 <div class="year-summary"><span class="eyebrow">${state.archiveMode==='year'?'Jahressumme':'Monatssumme'}</span><div class="year-summary-grid"><div><small>Einnahmen</small><strong>${euro.format(total(shown,'income'))}</strong></div><div><small>Ausgaben</small><strong>${euro.format(total(shown,'expense'))}</strong></div></div></div>${list(shown)}`;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.archiveMode=b.dataset.mode;render()});document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const step=Number(b.dataset.step);state.archiveDate=state.archiveMode==='year'?new Date(year+step,0,1):new Date(year,d.getMonth()+step,1);render()});bindTransactions()}
function list(items){if(!items.length)return `<div class="empty">Noch keine Buchungen vorhanden.</div>`;return `<div class="transaction-list">${items.map(t=>`<button class="transaction ${t.status==='review'?'needs-review':''}" data-id="${t.id}"><span class="tx-icon">${initials(t.name)}</span><span class="tx-main"><strong>${escapeHtml(t.name)}${t.status==='review'?'<i class="warning">!</i>':''}</strong><small>${formatTransactionDate(t.date)} · ${escapeHtml(t.method)}</small></span><span class="tx-value ${t.type==='income'?'in':''}">${t.type==='income'?'+':'−'} ${euro.format(t.amount)}</span></button>`).join('')}</div>`}
function statistics(){const year=state.statsYear,months=Array.from({length:12},(_,month)=>{const items=state.transactions.filter(t=>{const d=new Date(t.date);return d.getFullYear()===year&&d.getMonth()===month});return {month,inc:total(items,'income'),exp:total(items,'expense')}}),max=Math.max(1,...months.flatMap(m=>[m.inc,m.exp])),yearItems=state.transactions.filter(t=>new Date(t.date).getFullYear()===year),inc=total(yearItems,'income'),exp=total(yearItems,'expense');app.innerHTML=`<div class="page-head"><div><span class="eyebrow">Dein Jahr auf einen Blick</span><h1>Statistik</h1><p class="subtitle">Einnahmen und Ausgaben nach Monaten</p></div></div><div class="month-row stats-year"><button class="month-chip" data-year-step="-1">‹</button><h2>${year}</h2><button class="month-chip" data-year-step="1">›</button></div><div class="year-summary"><span class="eyebrow">Jahresübersicht</span><div class="year-summary-grid"><div><small>Einnahmen</small><strong>${euro.format(inc)}</strong></div><div><small>Ausgaben</small><strong>${euro.format(exp)}</strong></div><div><small>Differenz</small><strong class="${inc-exp>=0?'positive':'negative'}">${inc-exp>=0?'+':''}${euro.format(inc-exp)}</strong></div><div><small>Buchungen</small><strong>${yearItems.length}</strong></div></div></div><div class="stat-legend"><span><i class="legend-income"></i>Einnahmen</span><span><i class="legend-expense"></i>Ausgaben</span></div><div class="month-stat-list">${months.map(m=>`<button class="month-stat" data-stat-month="${m.month}"><strong>${new Intl.DateTimeFormat('de-DE',{month:'short'}).format(new Date(year,m.month,1))}</strong><span class="stat-bars"><i class="stat-bar income-bar" style="width:${m.inc/max*100}%"></i><i class="stat-bar expense-bar" style="width:${m.exp/max*100}%"></i></span><span class="stat-values"><small>+ ${euro.format(m.inc)}</small><small>− ${euro.format(m.exp)}</small></span></button>`).join('')}</div>`;document.querySelectorAll('[data-year-step]').forEach(b=>b.onclick=()=>{state.statsYear+=Number(b.dataset.yearStep);render()});document.querySelectorAll('[data-stat-month]').forEach(b=>b.onclick=()=>{state.archiveDate=new Date(year,Number(b.dataset.statMonth),1);state.archiveMode='month';state.route='archive';render()})}
function bindCommon(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.route=b.dataset.go;render()});bindTransactions()}
function bindTransactions(){document.querySelectorAll('.transaction').forEach(b=>b.onclick=()=>detail(b.dataset.id))}
function openNew(){open(`<div class="sheet-title"><h2>Neue Buchung</h2><button class="close">✕</button></div><p class="subtitle">Wie möchtest du sie hinzufügen?</p><div class="action-grid"><button class="action-card" id="manual"><span>✎</span><strong>Manuell</strong><small>Daten selbst eintragen</small></button><button class="action-card" id="upload"><span>↑</span><strong>Datei importieren</strong><small>PDF, CSV oder Bild</small></button><button class="action-card" id="paypalUpload"><span>P</span><strong>PayPal</strong><small>PDF oder bis zu 5 Screenshots</small></button><button class="action-card" id="camera"><span>◎</span><strong>Beleg scannen</strong><small>Foto aufnehmen</small></button><button class="action-card" id="shared"><span>↗</span><strong>Geteilt</strong><small>Aus anderer App</small></button></div>`);content.querySelector('#manual').onclick=()=>manualForm();content.querySelector('#upload').onclick=()=>{const i=document.querySelector('#fileInput');delete i.dataset.importMode;i.accept='.csv,.pdf,image/*';i.multiple=true;i.removeAttribute('capture');i.click()};content.querySelector('#paypalUpload').onclick=()=>{const i=document.querySelector('#fileInput');i.dataset.importMode='paypal';i.accept='.pdf,application/pdf,image/*';i.multiple=true;i.removeAttribute('capture');i.click()};content.querySelector('#camera').onclick=()=>{const i=document.querySelector('#fileInput');delete i.dataset.importMode;i.accept='image/*';i.multiple=false;i.setAttribute('capture','environment');i.click()};content.querySelector('#shared').onclick=()=>showToast('Geteilte Dateien erscheinen nach Installation als App.')}
function manualForm(existing,preset={}){
 const t=existing||{name:'',amount:'',type:'expense',date:new Date().toISOString().slice(0,10),method:'Girokonto',status:'confirmed',source:'Manuell',...preset},accounts=window.MoneybrainAccounts,selectedAccount=t.accountId||accounts.accountForTransaction(t)?.id||accounts.active()[0]?.id||'';
 open(`<div class="sheet-title"><h2>${existing?'Buchung ändern':'Manuell buchen'}</h2><button class="close">✕</button></div><form class="form" id="txForm"><div class="field"><label>Empfänger / Sender</label><input name="name" value="${escapeHtml(t.name)}" required placeholder="z. B. REWE Markt"></div><div class="split"><div class="field"><label>Betrag</label><input name="amount" type="number" min="0.01" step="0.01" value="${t.amount}" required></div><div class="field"><label>Art</label><select name="type"><option value="expense" ${t.type==='expense'?'selected':''}>Ausgabe</option><option value="income" ${t.type==='income'?'selected':''}>Einnahme</option></select></div></div><div class="field"><label>Datum</label><input name="date" type="date" value="${String(t.date).slice(0,10)}" required></div><div class="field"><label>Geldtopf</label><select name="accountId" required>${accounts.active().map(account=>`<option value="${account.id}" ${selectedAccount===account.id?'selected':''}>${escapeHtml(account.name)}</option>`).join('')}</select></div><div class="field"><label>Notiz</label><textarea name="note" placeholder="Zusätzliche Angaben, z. B. Datum der Abbuchung">${escapeHtml(t.note||'')}</textarea></div><button class="primary" type="submit">${existing?'Änderungen speichern':'Buchung speichern'}</button></form>`);
 content.querySelector('#txForm').onsubmit=event=>{event.preventDefault();const form=new FormData(event.target),data=Object.fromEntries(form),account=accounts.all().find(item=>item.id===data.accountId);data.amount=Number(data.amount);data.date=new Date(`${data.date}T12:00:00`).toISOString();data.method=account?.name||t.method||'Sonstiges';data.status=t.amountUncertain?'confirmed':(t.status||'confirmed');data.source=t.source||'Manuell';if(existing){Object.assign(existing,data);delete existing.amountUncertain;if(!state.transactions.some(item=>item.id===existing.id))state.transactions.push(existing)}else{data.id=crypto.randomUUID();state.transactions.push(data)}save();sheet.close();render();showToast(existing?'Buchung aktualisiert':'Buchung gespeichert')};
}
function bankDateNote(type,date){return (type==='income'?'Auf das Konto gebucht: ':'Vom Konto abgebucht: ')+new Date(date).toLocaleDateString('de-DE')}
function displayedTransactionNote(t){if(t.bankDate){const base=bankDateNote(t.type,t.bankDate),details=String(t.source||'').includes('Konto-Screenshot')&&String(t.note||'').includes('\n')?String(t.note).slice(String(t.note).indexOf('\n')):'';return base+details}return t.note||''}
function detail(id){
 const t=state.transactions.find(item=>item.id===id);if(!t)return;const match=state.transactions.find(item=>item.id===t.matchId),shownNote=displayedTransactionNote(t),parts=window.MoneybrainMovements.splitsFor(t.id),accounts=window.MoneybrainAccounts;
 const splitHtml=parts.length?`<div class="transaction-splits"><span class="eyebrow">Aufteilung</span>${parts.map(part=>{const transfer=part.transferId?window.MoneybrainMovements.allTransfers().find(item=>item.id===part.transferId):null,target=transfer?accounts.all().find(account=>account.id===transfer.targetAccountId):accounts.all().find(account=>account.id===(part.accountId||t.accountId));return `<div class="split-entry"><span><strong>${part.kind==='transfer'?'<i class="transfer-marker">Transfer</i>':escapeHtml(part.label||'Ausgabe')}</strong><small>${part.kind==='transfer'?'Nach ':''}${escapeHtml(target?.name||'Geldtopf nicht gefunden')}</small></span><b>${euro.format(part.amount)}</b></div>`}).join('')}</div>`:'';
 open(`<div class="sheet-title"><div><span class="eyebrow">${t.type==='income'?'Sender':'Empfänger'}</span><h2>${escapeHtml(t.name)}</h2></div><button class="close">✕</button></div><div class="detail-amount ${t.type==='income'?'in':'out'}">${t.type==='income'?'+':'−'} ${euro.format(t.amount)}</div><div class="detail-list"><div class="detail-row"><span>Datum</span><strong>${formatTransactionDate(t.date,true)}</strong></div><div class="detail-row"><span>Geldtopf</span><strong>${escapeHtml(accounts.accountForTransaction(t)?.name||'Nicht zugeordnet')}</strong></div><div class="detail-row"><span>Quelle</span><strong>${escapeHtml(t.source)}</strong></div><div class="detail-row"><span>Status</span><strong class="status ${t.status==='confirmed'?'ok':'open'}">${t.status==='confirmed'?'Geprüft & bestätigt':'Prüfung nötig'}</strong></div>${shownNote?`<div class="detail-row note-row"><span>Notiz</span><details><summary>Notiz vollständig anzeigen</summary><div>${escapeHtml(shownNote)}</div></details></div>`:''}</div>${splitHtml}${match?`<div class="review-box"><strong>Mögliche Doppelbuchung</strong><p>${escapeHtml(match.name)} · ${euro.format(match.amount)} · ${formatTransactionDate(match.date,true)}<br>Datum und Empfänger weichen leicht ab.</p><div class="review-actions"><button class="secondary" id="separate">Verschieden</button><button class="secondary" id="merge">Zusammenführen</button></div></div>`:''}<button class="secondary split-booking-button" id="splitBooking">${parts.length?'Aufteilung bearbeiten':'Buchung aufteilen'}</button><div class="split" style="margin-top:10px"><button class="secondary" id="edit">Ändern</button><button class="secondary danger" id="delete">Löschen</button></div>`);
 content.querySelector('#splitBooking').onclick=()=>openSplitForm(t);content.querySelector('#edit').onclick=()=>manualForm(t);content.querySelector('#delete').onclick=()=>{if(confirm('Diese Buchung wirklich löschen?')){window.MoneybrainMovements.removeTransaction(id);state.transactions=state.transactions.filter(item=>item.id!==id);save();sheet.close();render();showToast('Buchung gelöscht')}};
 content.querySelector('#merge')?.addEventListener('click',()=>{const keep={...t,name:t.name.length<=match.name.length?t.name:match.name,status:'confirmed',matchId:null,note:`Abgeglichen aus ${t.source} und ${match.source}`};state.transactions=state.transactions.filter(item=>item.id!==t.id&&item.id!==match.id);state.transactions.push(keep);save();sheet.close();render();showToast('Doppelbuchung zusammengeführt')});content.querySelector('#separate')?.addEventListener('click',()=>{t.status=match.status='confirmed';t.matchId=match.matchId=null;save();sheet.close();render();showToast('Als getrennte Buchungen bestätigt')});
}
function openSplitForm(transaction){
 const movements=window.MoneybrainMovements,accounts=window.MoneybrainAccounts.active(),existing=movements.splitsFor(transaction.id),existingTransfers=movements.allTransfers(),initial=existing.length?existing.map(part=>{const transfer=existingTransfers.find(item=>item.id===part.transferId);return {kind:part.kind,amount:part.amount,label:part.label,accountId:part.accountId||transaction.accountId||'',targetAccountId:transfer?.targetAccountId||''}}):[{kind:transaction.type,amount:Number(transaction.amount),label:'',accountId:transaction.accountId||''},{kind:transaction.type,amount:0,label:'',accountId:''}];
 if(!accounts.length){showToast('Bitte zuerst einen Geldtopf anlegen');return}
 const accountOptions=accounts.map(account=>`<option value="${account.id}" ${transaction.accountId===account.id?'selected':''}>${escapeHtml(account.name)}</option>`).join('');
 open(`<div class="sheet-title"><h2>Buchung aufteilen</h2><button class="close">✕</button></div><p class="subtitle">Gesamtbetrag ${euro.format(transaction.amount)}. Füge beliebig viele Geldtöpfe und Teilbeträge hinzu.</p><form class="form" id="splitForm"><div class="field"><label>Belasteter Geldtopf</label><select name="sourceAccountId" required><option value="">Bitte auswählen</option>${accountOptions}</select></div><div id="splitRows"></div><button class="secondary add-split-row" type="button" id="addSplitRow">＋ Weiteren Teilbetrag hinzufügen</button><div class="split-sum"><span>Summe<small id="splitDifference"></small></span><strong id="splitSum">${euro.format(0)}</strong></div><button class="primary" id="saveSplit" type="submit" disabled>Aufteilung speichern</button></form>`);
 const form=content.querySelector('#splitForm'),container=content.querySelector('#splitRows'),sourceSelect=form.querySelector('[name="sourceAccountId"]'),targetOptions=selected=>`<option value="">Bitte auswählen</option>${accounts.filter(account=>account.id!==sourceSelect.value).map(account=>`<option value="${account.id}" ${selected===account.id?'selected':''}>${escapeHtml(account.name)}</option>`).join('')}`;
 const addRow=(part={kind:transaction.type,amount:0,label:'',accountId:'',targetAccountId:''})=>{const row=document.createElement('fieldset');row.className='split-form-row';row.innerHTML=`<button class="remove-split" type="button" aria-label="Teilbetrag entfernen">✕</button><div class="split"><div class="field"><label>Art</label><select name="kind"><option value="${transaction.type}" ${part.kind!=='transfer'?'selected':''}>${transaction.type==='income'?'Einnahme':'Ausgabe'}</option><option value="transfer" ${part.kind==='transfer'?'selected':''}>Transfer</option></select></div><div class="field"><label>Betrag</label><input name="amount" type="number" min="0.01" step="0.01" value="${part.amount||''}" required></div></div><div class="field split-account"><label>Geldtopf</label><select name="accountId">${accountOptions.replace(`value="${part.accountId}"`,`value="${part.accountId}" selected`)}</select></div><div class="field split-label"><label>Bezeichnung</label><input name="label" value="${escapeHtml(part.label)}" placeholder="z. B. Lebensmittel"></div><div class="field split-target"><label>Ziel-Geldtopf</label><select name="targetAccountId">${targetOptions(part.targetAccountId)}</select></div>`;container.appendChild(row);const kind=row.querySelector('[name="kind"]'),account=row.querySelector('.split-account'),accountSelect=account.querySelector('select'),target=row.querySelector('.split-target'),targetSelect=target.querySelector('select');const refreshType=()=>{const transfer=kind.value==='transfer';account.hidden=transfer;target.hidden=!transfer;accountSelect.required=!transfer;targetSelect.required=transfer;refreshSum()};kind.onchange=refreshType;accountSelect.onchange=refreshSum;targetSelect.onchange=refreshSum;refreshType();row.querySelector('.remove-split').onclick=()=>{if(container.children.length>1){row.remove();refreshSum()}};row.querySelector('[name="amount"]').oninput=refreshSum};
 const refreshSum=()=>{const total=Math.round(Number(transaction.amount)*100),sum=[...container.querySelectorAll('[name="amount"]')].reduce((value,input)=>value+Math.round(Number(input.value||0)*100),0),difference=total-sum,rowsValid=[...container.children].every(row=>row.querySelector('[name="kind"]').value==='transfer'?Boolean(row.querySelector('[name="targetAccountId"]').value):Boolean(row.querySelector('[name="accountId"]').value)),valid=difference===0&&sum>0&&Boolean(sourceSelect.value)&&rowsValid;content.querySelector('#splitSum').textContent=euro.format(sum/100);content.querySelector('#splitSum').className=valid?'positive':'negative';content.querySelector('#splitDifference').textContent=valid?'Keine Differenz':difference?`Differenz: ${euro.format(difference/100)}`:'Bitte alle Geldtöpfe auswählen';content.querySelector('#saveSplit').disabled=!valid};
 initial.forEach(addRow);refreshSum();content.querySelector('#addSplitRow').onclick=()=>{addRow();refreshSum()};
 sourceSelect.onchange=()=>{container.querySelectorAll('[name="targetAccountId"]').forEach(select=>{const selected=select.value;select.innerHTML=targetOptions(selected)});refreshSum()};
 form.onsubmit=event=>{event.preventDefault();try{const parts=[...container.children].map(row=>({kind:row.querySelector('[name="kind"]').value,amount:Number(row.querySelector('[name="amount"]').value),label:row.querySelector('[name="label"]').value,accountId:row.querySelector('[name="accountId"]').value,targetAccountId:row.querySelector('[name="targetAccountId"]').value}));transaction.accountId=sourceSelect.value;transaction.method=accounts.find(account=>account.id===transaction.accountId)?.name||transaction.method;movements.replaceSplits(transaction,parts);save();sheet.close();render();showToast('Buchungsaufteilung gespeichert')}catch(error){showToast(error.message)}};
}
function open(html){content.innerHTML='<div class="sheet-handle"></div>'+html;const method=content.querySelector('#txForm select[name="method"]');if(method&&html.includes('Manuell buchen'))method.value=settings.defaultMethod;content.querySelector('.close')?.addEventListener('click',()=>sheet.close());sheet.showModal()}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;render()});
document.querySelector('#profileBtn').onclick=()=>{const cloud=window.MoneybrainCloud;if(!cloud?.isConfigured()){showToast('Cloud-Speicher noch nicht eingerichtet');return}open(`<div class="sheet-title"><h2>Moneybrain-Konto</h2><button class="close">✕</button></div><div class="detail-list"><div class="detail-row"><span>Cloud-Speicher</span><strong class="status ok" id="cloudStatus">${cloud.isSignedIn()?'Verbunden':'Nicht angemeldet'}</strong></div></div><button class="secondary" style="width:100%" id="logout">Abmelden</button>`);content.querySelector('#logout').onclick=()=>cloud.signOut()};
document.querySelector('#settingsBtn').onclick=()=>openSettings();
function openSettings(){const cloud=window.MoneybrainCloud,methods=['Girokonto','PayPal','Bar','Kreditkarte','Sonstiges'];open(`<div class="sheet-title"><h2>Einstellungen</h2><button class="close">✕</button></div><form class="form" id="settingsForm"><div class="detail-list"><div class="detail-row"><span>Cloud-Speicher</span><strong class="status ${cloud?.isSignedIn()?'ok':'open'}" id="cloudStatus">${cloud?.isSignedIn()?'Verbunden':'Nicht angemeldet'}</strong></div></div><div class="field"><label>Standard-Zahlungsweg</label><select name="defaultMethod">${methods.map(x=>`<option ${settings.defaultMethod===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Währung</label><select name="currency">${[['EUR','Euro (€)'],['USD','US-Dollar ($)'],['GBP','Britisches Pfund (£)']].map(([v,l])=>`<option value="${v}" ${settings.currency===v?'selected':''}>${l}</option>`).join('')}</select></div><button class="primary" type="submit">Einstellungen speichern</button></form><div class="settings-actions"><button class="secondary" id="exportBackup">Sicherung exportieren</button><button class="secondary" id="importBackup">Sicherung wiederherstellen</button></div><p class="settings-hint">Die Sicherungsdatei enthält deine Buchungen und Einstellungen. Bewahre sie an einem sicheren Ort auf.</p>${cloud?.isSignedIn()?'<button class="secondary danger settings-logout" id="settingsLogout">Abmelden</button>':''}`);content.querySelector('#settingsForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);settings={defaultMethod:String(f.get('defaultMethod')),currency:String(f.get('currency'))};localStorage.setItem('moneybrain.settings',JSON.stringify(settings));euro=new Intl.NumberFormat('de-DE',{style:'currency',currency:settings.currency});sheet.close();render();showToast('Einstellungen gespeichert')};content.querySelector('#exportBackup').onclick=exportBackup;content.querySelector('#importBackup').onclick=()=>document.querySelector('#backupInput').click();content.querySelector('#settingsLogout')?.addEventListener('click',()=>cloud.signOut())}
function exportBackup(){const data={app:'Moneybrain',version:1,exportedAt:new Date().toISOString(),settings,transactions:cleanStoredTransactions(state.transactions)},blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`moneybrain-sicherung-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast('Sicherung erstellt')}
document.querySelector('#backupInput').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const data=JSON.parse(await file.text());if(data.app!=='Moneybrain'||!Array.isArray(data.transactions))throw new Error('invalid');if(!confirm(`${data.transactions.length} Buchungen aus dieser Sicherung wiederherstellen? Der aktuelle Bestand wird ersetzt.`))return;state.transactions=cleanStoredTransactions(data.transactions);if(data.settings){settings={...settings,...data.settings};localStorage.setItem('moneybrain.settings',JSON.stringify(settings));euro=new Intl.NumberFormat('de-DE',{style:'currency',currency:settings.currency})}save();sheet.close();render();showToast('Sicherung wiederhergestellt')}catch{showToast('Keine gültige Moneybrain-Sicherung')}};
document.querySelector('#fileInput').onchange=async e=>{
 const files=[...e.target.files],importMode=e.target.dataset.importMode;delete e.target.dataset.importMode;e.target.multiple=true;if(!files.length)return;
 if(importMode==='paypal'){e.target.value='';if(files.length>5){showToast('Bitte höchstens 5 PayPal-Screenshots auswählen');return}return showPayPalBatchImport(files)}
 if(files.every(f=>f.name.toLowerCase().endsWith('.csv'))){for(const file of files)await importCsv(file);sheet.close();render();showToast(`${files.length} CSV-Datei(en) importiert`)}
 else if(files.length>1){isBankScreenshotBatch(files)?showBankScreenshotDisabled():(files.every(isImageFile)?showSmartImageBatchImport(files):(files.every(isPayPalEvidenceFile)?showPayPalBatchImport(files):showReceiptBatchImport(files)))}
 else{open(`<div class="sheet-title"><h2>Import pr?fen</h2><button class="close">&times;</button></div><div class="import-box"><strong>1 Datei bereit</strong><p>${escapeHtml(files[0].name)}</p></div><button class="primary" id="createFromFile">Datei pr?fen</button>`);content.querySelector('#createFromFile').onclick=()=>showDocumentImport(files[0])}
 e.target.value='';
};
async function importCsv(file){const text=await file.text(),lines=text.trim().split(/\r?\n/),sep=lines[0].includes(';')?';':',';for(const line of lines.slice(1)){const c=line.split(sep).map(x=>x.replace(/^"|"$/g,'').trim());if(c.length<3)continue;const parsed=Number(String(c[2]).replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''));const date=parseDate(c[0]);if(!date||!Number.isFinite(parsed))continue;state.transactions.push({id:crypto.randomUUID(),date:date.toISOString(),name:c[1]||'Unbekannt',amount:Math.abs(parsed),type:parsed>=0?'income':'expense',method:'Girokonto',status:'review',source:'CSV'})}save()}
function parseDate(s){const p=s.split(/[.\/-]/);if(p.length!==3)return null;return p[0].length===4?new Date(+p[0],+p[1]-1,+p[2],12):new Date(+p[2],+p[1]-1,+p[0],12)}
function formatTransactionDate(value,full=false){const date=new Date(value);if(Number.isNaN(date.getTime()))return 'Datum fehlt';return full?date.toLocaleDateString('de-DE'):shortDate.format(date)}
function showToast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function initials(s){return s.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function capitalize(s){return s.charAt(0).toUpperCase()+s.slice(1)}
function escapeHtml(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
window.moneybrainGetTransactions=()=>cleanStoredTransactions(state.transactions);
window.moneybrainApplyCloudTransactions=(items,updatedAt)=>{const restored=cleanStoredTransactions(items);state.transactions=restored;localStorage.setItem('moneybrain.transactions',JSON.stringify(restored));localStorage.setItem('moneybrain.localUpdatedAt',updatedAt||new Date().toISOString());backupTransactions(restored);render()};
window.render=render;
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).then(registration=>registration.update()).catch(error=>console.warn('App-Update konnte nicht geprüft werden.',error));
(async()=>{render();await restorePersistentTransactions();await window.MoneybrainCloud?.init()})();

handleSharedLaunch();
async function handleSharedLaunch(){
 const params=new URLSearchParams(location.search);
 if(params.has('shareError')){showToast('Die geteilte Datei konnte nicht gelesen werden.');history.replaceState({},'',location.pathname);return}
 if(!params.has('shared'))return;
 history.replaceState({},'',location.pathname);
 const shared=await readLatestShare();
 if(!shared){showToast('Keine geteilte Datei gefunden.');return}
 const files=shared.files||[],names=files.length?files.map(file=>escapeHtml(file.name||'Kontoauszug')).join('<br>'):'Geteilter Inhalt';
 open(`<div class="sheet-title"><h2>Kontoauszug erhalten</h2><button class="close">✕</button></div><div class="import-box"><strong>${files.length||1} Datei(en) aus deiner Bank-App</strong><p>${names}</p></div><p class="subtitle" style="margin-top:14px">Der Kontoauszug wurde nur auf diesem Gerät gespeichert. Prüfe und ergänze die Buchungsdaten vor der Übernahme.</p><button class="primary" id="reviewShared">Import prüfen</button>`);
 content.querySelector('#reviewShared').onclick=()=>showDocumentImport(files[0]);
}
function openShareDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open('moneybrain-share',1);request.onupgradeneeded=()=>request.result.createObjectStore('inbox',{keyPath:'id',autoIncrement:true});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function readLatestShare(){try{const db=await openShareDb();return await new Promise((resolve,reject)=>{const tx=db.transaction('inbox','readwrite'),store=tx.objectStore('inbox'),request=store.openCursor(null,'prev');request.onsuccess=()=>{const cursor=request.result;if(!cursor){resolve(null);return}const value=cursor.value;cursor.delete();resolve(value)};request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close()})}catch{return null}}
async function showStatementOnly(file){
 if(!file){showToast('Der Kontoauszug enthält keine Datei.');return}
 const button=content.querySelector('#reviewShared,#createFromFile');button.disabled=true;button.textContent='Kontoauszug wird gelesen …';
 try{
  const result=await window.parseDeutscheBankStatement(file);
  open('<div class="sheet-title"><h2>Importübersicht</h2><button class="close">✕</button></div><p class="subtitle">'+result.pages+' Seiten wurden vollständig gelesen.'+(result.cashMovements?' '+result.cashMovements+' Bargeldbewegung(en) über '+euro.format(result.cashExcluded)+' werden nicht berücksichtigt.':'')+'</p><div class="year-summary"><span class="eyebrow">Erkannte Buchungen</span><strong style="font-size:30px;display:block;margin-top:8px">'+result.transactions.length+'</strong><div class="year-summary-grid"><div><small>Einnahmen</small><strong>'+euro.format(result.income)+'</strong></div><div><small>Ausgaben</small><strong>'+euro.format(result.expense)+'</strong></div></div></div><div class="detail-list"><div class="detail-row"><span>Status</span><strong class="status ok">Kontoauszug geprüft</strong></div><div class="detail-row"><span>Übernahme</span><strong>Alle Buchungen</strong></div></div><button class="primary" id="importStatement">Alle '+result.transactions.length+' Buchungen übernehmen</button><button class="secondary" style="width:100%" id="previewStatement">Buchungen ansehen</button>');
  content.querySelector('#previewStatement').onclick=()=>{open('<div class="sheet-title"><h2>Erkannte Buchungen</h2><button class="close">✕</button></div><p class="subtitle">'+result.transactions.length+' Buchungen, chronologisch sortiert</p>'+list([...result.transactions].sort((a,b)=>new Date(b.date)-new Date(a.date))))};
  content.querySelector('#importStatement').onclick=()=>importStatementTransactions(result.transactions);
 }catch(error){open('<div class="sheet-title"><h2>Import nicht möglich</h2><button class="close">✕</button></div><div class="review-box"><strong>Kontoauszug nicht erkannt</strong><p>'+escapeHtml(error.message)+'</p></div>')}
}
const matchDay=86400000;
function isGenericBankMerchant(name){return /^(Kartenzahlung|Unbekannte Buchung)$/i.test(String(name||''))}
function transactionNameKey(value){return String(value||'').toLowerCase().replace(/gmbh|markt|marken-discount|filiale|[^a-z0-9]/g,'')}
function sameTransactionMerchant(a,b){const left=transactionNameKey(a),right=transactionNameKey(b);return left.length>2&&right.length>2&&(left.includes(right)||right.includes(left))}
function sourceParts(value){return String(value||'').split(/\s*\+\s*/).filter(Boolean)}
function combinedSource(a,b){return [...new Set([...sourceParts(a),...sourceParts(b)])].join(' + ')}
function sourceFamily(value){const text=String(value||'');if(/Kontoauszug|CSV/i.test(text))return 'bank';if(/PayPal/i.test(text))return 'paypal';if(/Kassenbon/i.test(text))return 'receipt';if(/Manuell/i.test(text))return 'manual';return text.toLowerCase()}
function reconcileAllTransactions(items){
 const result=[];
 for(const original of cleanStoredTransactions(items)){
  const item={...original},candidates=result.filter(existing=>existing.type===item.type&&Math.abs(Number(existing.amount)-Number(item.amount))<0.005&&Math.abs(new Date(existing.date)-new Date(item.date))<=5*matchDay&&sourceFamily(existing.source)!==sourceFamily(item.source));
  const strong=candidates.filter(existing=>sameTransactionMerchant(existing.name,item.name));
  if(strong.length===1){
   const existing=strong[0],bank=[existing,item].find(value=>sourceFamily(value.source)==='bank'),paypal=[existing,item].find(value=>sourceFamily(value.source)==='paypal'),receipt=[existing,item].find(value=>sourceFamily(value.source)==='receipt');
   const preferred=receipt||paypal||existing;
   Object.assign(existing,preferred,{id:existing.id,source:combinedSource(existing.source,item.source),status:'confirmed',method:paypal?'PayPal':(preferred.method||existing.method),bankDate:bank?(bank.bankDate||bank.date):(existing.bankDate||item.bankDate),note:bank?bankDateNote(item.type,bank.bankDate||bank.date):(preferred.note||existing.note)});delete existing.matchId;continue;
  }
  if(candidates.length===1){item.status='review';item.matchId=candidates[0].id;candidates[0].status='review';candidates[0].matchId=item.id}
  result.push(item);
 }
 return result;
}
function transactionCandidates(transaction,sourceTest){return state.transactions.filter(item=>sourceTest(item)&&item.type===transaction.type&&Math.abs(Number(item.amount)-Number(transaction.amount))<0.005&&Math.abs(new Date(item.date)-new Date(transaction.date))<=5*matchDay)}
function bankReferenceFromNote(note){const text=String(note||'');return (text.match(/Kundenreferenz\s*([A-Z0-9()+?._-]+)/i)||text.match(/Mandatsreferenz\s*([A-Z0-9()+?._-]+)/i))?.[1]||''}
function sameBankImportIdentity(a,b){
 if(a.type!==b.type||Math.abs(Number(a.amount)-Number(b.amount))>=0.005)return false;
 if(String(a.date).slice(0,10)!==String(b.date).slice(0,10))return false;
 if(!sameTransactionMerchant(a.name,b.name)&&transactionNameKey(a.name)!==transactionNameKey(b.name))return false;
 const leftRef=bankReferenceFromNote(a.note),rightRef=bankReferenceFromNote(b.note);return !leftRef||!rightRef||leftRef===rightRef;
}
function importStatementTransactions(items){
 const times=items.map(item=>new Date(item.date).getTime()),rangeStart=Math.min(...times)-matchDay,rangeEnd=Math.max(...times)+matchDay;
 localStorage.setItem('moneybrain.bankReference',JSON.stringify(items.map(item=>({name:item.name,amount:item.amount,type:item.type,date:item.date,valueDate:item.valueDate||item.date}))));
 let replacedScreenshots=0;
 state.transactions=state.transactions.filter(item=>{const source=String(item.source||''),time=new Date(item.bankDate||item.date).getTime();if(source.includes('Konto-Screenshot')&&!source.includes('Kassenbon')&&time>=rangeStart&&time<=rangeEnd){replacedScreenshots++;return false}return true});
 let merged=0,review=0,added=0;
 items.forEach(bank=>{
  const existingStatements=state.transactions.filter(item=>String(item.source||'').includes('Kontoauszug')&&sameBankImportIdentity(item,bank));
  if(existingStatements.length===1){const existing=existingStatements[0];Object.assign(existing,{name:bank.name,amount:bank.amount,type:bank.type,date:bank.date,valueDate:bank.valueDate||bank.date,method:bank.method,status:'confirmed',note:bank.note});delete existing.matchId;merged++;return}
  const screenshots=state.transactions.filter(item=>String(item.source||'').includes('Konto-Screenshot')&&item.type===bank.type&&Math.abs(Number(item.amount)-Number(bank.amount))<0.005&&Math.abs(new Date(item.bankDate||item.date)-new Date(bank.date))<=matchDay&&sameTransactionMerchant(item.name,bank.name));
  if(screenshots.length===1){const screenshot=screenshots[0],hasReceipt=String(screenshot.source||'').includes('Kassenbon');Object.assign(screenshot,{bankDate:bank.date,valueDate:bank.valueDate||bank.date,method:bank.method||screenshot.method,status:'confirmed',source:'Kontoauszug + Konto-Screenshot'+(hasReceipt?' + Kassenbon':''),note:bankDateNote(bank.type,bank.date)});delete screenshot.matchId;merged++;return}
  if(screenshots.length>1){bank.status='review';state.transactions.push(bank);review++;added++;return}
  const candidates=transactionCandidates(bank,item=>String(item.source||'').includes('Kassenbon'));
  const matching=candidates.filter(item=>sameTransactionMerchant(item.name,bank.name));
  if(matching.length===1){const receipt=matching[0];Object.assign(receipt,{bankDate:bank.date,valueDate:bank.valueDate||bank.date,method:bank.method||receipt.method,status:'confirmed',source:'Kontoauszug + Kassenbon',note:bankDateNote(bank.type,bank.date)});delete receipt.matchId;merged++;return}
  if(candidates.length===1){bank.status='review';bank.matchId=candidates[0].id;candidates[0].status='review';candidates[0].matchId=bank.id;review++}else if(candidates.length>1){bank.status='review';review++}
  state.transactions.push(bank);added++;
 });
 save();sheet.close();state.route='transactions';state.filter='all';render();
 showToast(merged+' abgeglichen, '+added+' übernommen'+(review?', '+review+' zur Prüfung':'')+'; Bargeld ignoriert');
}

function isBankScreenshotFile(file){return /deutsche.?bank|konto.?screenshot|konto.?umsatz/i.test(String(file?.name||''))}
function isPayPalEvidenceFile(file){return /paypal/i.test(String(file?.name||''))&&(String(file?.type||'').startsWith('image/')||/\.pdf$/i.test(file.name))}
function isImageFile(file){return String(file?.type||'').startsWith('image/')||/\.(png|jpe?g|webp)$/i.test(String(file?.name||''))}
function isBankScreenshotBatch(files){return files.length>0&&files.every(file=>file.type.startsWith('image/')||/\.(png|jpe?g|webp)$/i.test(file.name))&&files.some(isBankScreenshotFile)}
function showBankScreenshotDisabled(){
 open('<div class="sheet-title"><h2>Bank-Screenshots deaktiviert</h2><button class="close">&times;</button></div><div class="review-box"><strong>Bitte Kontoauszug oder Kontoumsaetze als PDF verwenden</strong><p>Bank-Screenshots werden wegen unzuverlaessiger Betrags- und Haendlererkennung nicht mehr verarbeitet. Kassenbons und Rechnungen als Bild oder PDF funktionieren weiterhin.</p></div>');
}
async function showDocumentImport(file){
 if(!file){showToast('Keine Datei gefunden.');return}
 if(/kontoauszug|kontoumsa(?:e|\u00e4)tze/i.test(file.name))return showStatementOnly(file);
 if(isBankScreenshotFile(file))return showBankScreenshotDisabled();
 if(isPayPalEvidenceFile(file))return showPayPalImport(file);
 if(file.type==='application/pdf'||/\.pdf$/i.test(file.name)){try{const transactions=await window.parsePayPalActivity(file,()=>{});return showPayPalReview(transactions)}catch(error){if(!/kein PayPal-Aktivit/i.test(error.message)&&!/kein PayPal-Aktiv/i.test(error.message)&&!/kein PayPal/i.test(error.message))console.warn(error)}}
 if(String(file.type||'').startsWith('image/')||/\.(png|jpe?g|webp)$/i.test(file.name)){try{const transactions=await window.parsePayPalActivity(file,()=>{});return showPayPalReview(transactions)}catch(error){console.info('Kein PayPal-Screenshot, Belegerkennung wird verwendet:',error.message)}}
 return showReceiptImport(file);
}
async function showPayPalImport(file){
 try{
  const transactions=await window.parsePayPalActivity(file,message=>{const button=content.querySelector('#reviewShared,#createFromFile');if(button)button.textContent=message});
  showPayPalReview(transactions);
 }catch(error){open('<div class="sheet-title"><h2>Import nicht möglich</h2><button class="close">✕</button></div><div class="review-box"><strong>PayPal-Nachweis nicht erkannt</strong><p>'+escapeHtml(error.message)+'</p></div>')}
}
async function showPayPalBatchImport(files){
 if(files.length>5){showToast('Bitte höchstens 5 PayPal-Screenshots auswählen');return}
 open('<div class="sheet-title"><h2>PayPal wird gelesen</h2><button class="close">✕</button></div><div class="import-box"><strong id="paypalBatchProgress">0 von '+files.length+' Dateien geprüft</strong><p>App- und Browser-Screenshots werden gemeinsam ausgewertet.</p></div>');
 const transactions=[],errors=[];for(let index=0;index<files.length;index++){const file=files[index];try{transactions.push(...await window.parsePayPalActivity(file,message=>{const progress=content.querySelector('#paypalBatchProgress');if(progress)progress.textContent=(index+1)+' von '+files.length+': '+message}))}catch(error){errors.push({file,error})}const progress=content.querySelector('#paypalBatchProgress');if(progress)progress.textContent=(index+1)+' von '+files.length+' Dateien geprüft'}
 const unique=window.dedupePayPalTransactions?window.dedupePayPalTransactions(transactions):transactions;
 if(!unique.length){open('<div class="sheet-title"><h2>Import nicht möglich</h2><button class="close">✕</button></div><div class="review-box"><strong>Keine PayPal-Buchungen erkannt</strong><p>Die ausgewählten Dateien enthielten keine sicher lesbaren PayPal-Aktivitäten.</p></div>');return}
 showPayPalReview(unique);
}
async function showSmartImageBatchImport(files){
 if(files.length>5)return showReceiptBatchImport(files);
 open('<div class="sheet-title"><h2>Bilder werden gelesen</h2><button class="close">✕</button></div><div class="import-box"><strong id="paypalBatchProgress">0 von '+files.length+' Bildern geprüft</strong><p>Moneybrain prüft zuerst den Bildinhalt auf PayPal-Aktivitäten.</p></div>');
 const transactions=[];
 for(let index=0;index<files.length;index++){
  try{transactions.push(...await window.parsePayPalActivity(files[index],message=>{const progress=content.querySelector('#paypalBatchProgress');if(progress)progress.textContent=(index+1)+' von '+files.length+': '+message}))}catch(error){console.info('Kein PayPal-Screenshot:',files[index].name,error.message)}
  const progress=content.querySelector('#paypalBatchProgress');if(progress)progress.textContent=(index+1)+' von '+files.length+' Bildern geprüft';
 }
 const unique=window.dedupePayPalTransactions?window.dedupePayPalTransactions(transactions):transactions;
 if(unique.length)return showPayPalReview(unique);
 showReceiptBatchImport(files);
}
function showPayPalReview(transactions){open(`<div class="sheet-title"><h2>PayPal prüfen</h2><button class="close">✕</button></div><p class="subtitle">Korrigiere die erkannten Angaben vor dem Speichern. Abgewählte Buchungen werden nicht übernommen.</p><form class="paypal-review-form" id="paypalReviewForm">${transactions.map((item,index)=>`<fieldset class="paypal-review-card"><label class="paypal-include"><input type="checkbox" name="include-${index}" checked> Buchung übernehmen</label><div class="field"><label>Händler / Sender</label><input name="name-${index}" value="${escapeHtml(item.name)}" required></div><div class="split"><div class="field"><label>Betrag</label><input name="amount-${index}" type="number" min="0.01" step="0.01" value="${Number(item.amount).toFixed(2)}" required></div><div class="field"><label>Art</label><select name="type-${index}"><option value="expense" ${item.type==='expense'?'selected':''}>Ausgabe</option><option value="income" ${item.type==='income'?'selected':''}>Einnahme</option></select></div></div><div class="split"><div class="field"><label>Datum</label><input name="date-${index}" type="date" value="${String(item.date).slice(0,10)}" required></div><div class="field"><label>Zahlungsweg</label><select name="method-${index}">${['PayPal','Girokonto','Kreditkarte','Bar','Sonstiges'].map(method=>`<option ${item.method===method?'selected':''}>${method}</option>`).join('')}</select></div></div><div class="field"><label>Notiz</label><textarea name="note-${index}">${escapeHtml(item.note||'')}</textarea></div></fieldset>`).join('')}<button class="primary" type="submit">Geprüfte Buchungen speichern</button></form>`);content.querySelector('#paypalReviewForm').onsubmit=e=>{e.preventDefault();const form=new FormData(e.currentTarget),reviewed=transactions.flatMap((item,index)=>{if(!form.get(`include-${index}`))return [];const amount=Number(form.get(`amount-${index}`)),date=String(form.get(`date-${index}`)||'');if(!Number.isFinite(amount)||amount<=0||!date)return [];return [{...item,name:cleanStoredPayPalName(form.get(`name-${index}`)),amount,type:String(form.get(`type-${index}`)),date:new Date(`${date}T12:00:00`).toISOString(),method:String(form.get(`method-${index}`)),note:String(form.get(`note-${index}`)||''),source:'PayPal-Nachweis',status:'confirmed'}]});if(!reviewed.length){showToast('Keine Buchung zur Übernahme ausgewählt');return}importPayPalTransactions(reviewed);save();sheet.close();state.route='transactions';state.filter='all';render();showToast(reviewed.length+' PayPal-Buchung(en) geprüft und gespeichert')}}
function importPayPalTransactions(transactions){
 for(const incoming of transactions){
  const existing=state.transactions.filter(item=>item.type===incoming.type&&Math.abs(Number(item.amount)-Number(incoming.amount))<0.005&&Math.abs(new Date(item.date)-new Date(incoming.date))<=7*86400000&&sameTransactionMerchant(cleanStoredPayPalName(item.name),incoming.name));
  if(existing.length===1){const saved=existing[0],bank=sourceFamily(saved.source)==='bank';Object.assign(saved,incoming,{id:saved.id,date:bank?incoming.date:(saved.date||incoming.date),bankDate:bank?(saved.bankDate||saved.date):saved.bankDate,source:combinedSource(saved.source,incoming.source),status:'confirmed',note:bank?bankDateNote(incoming.type,saved.bankDate||saved.date):(incoming.note||saved.note)});continue}
  state.transactions.push(incoming);
 }
}
async function showReceiptImport(file){
 try{
  const receipt=await window.parseRetailReceipt(file,message=>{const button=content.querySelector('#reviewShared,#createFromFile');if(button)button.textContent=message});
  open('<div class="sheet-title"><h2>Beleg erkannt</h2><button class="close">✕</button></div><div class="detail-amount out">− '+euro.format(receipt.amount)+'</div><div class="detail-list"><div class="detail-row"><span>Händler</span><strong>'+escapeHtml(receipt.name)+'</strong></div><div class="detail-row"><span>Datum</span><strong>'+new Date(receipt.date).toLocaleDateString('de-DE')+'</strong></div><div class="detail-row"><span>Zahlungsweg</span><strong>'+escapeHtml(receipt.method)+'</strong></div><div class="detail-row"><span>Status</span><strong class="status ok">Beleg geprüft</strong></div></div><button class="primary" id="importReceipt">Buchung übernehmen</button><button class="secondary" style="width:100%" id="editReceipt">Vorher ändern</button>');
  content.querySelector('#importReceipt').onclick=()=>importReceiptTransaction(receipt);
  content.querySelector('#editReceipt').onclick=()=>manualForm(receipt);
 }catch(error){open('<div class="sheet-title"><h2>Import nicht möglich</h2><button class="close">✕</button></div><div class="review-box"><strong>Beleg nicht erkannt</strong><p>'+escapeHtml(error.message)+'</p></div>')}
}
async function showReceiptBatchImport(files){
 if(files.some(file=>/kontoauszug|kontoumsa(?:e|\u00e4)tze/i.test(file.name))){open('<div class="sheet-title"><h2>Getrennter Import n?tig</h2><button class="close">&times;</button></div><div class="review-box"><strong>Kontoausz?ge bitte einzeln importieren</strong><p>Mehrere Kassenbons k?nnen gemeinsam gelesen werden. Bank-Screenshots werden aus Sicherheitsgr?nden nicht als Stapel uebernommen.</p></div>');return}
 open('<div class="sheet-title"><h2>Belege werden gelesen</h2><button class="close">&times;</button></div><div class="import-box"><strong id="batchProgress">0 von '+files.length+' Belegen gepr?ft</strong><p>PDFs und Bilder werden nacheinander ausgewertet.</p></div>');
 const receipts=[],errors=[];
 for(let index=0;index<files.length;index++){const file=files[index];try{receipts.push(await window.parseRetailReceipt(file,message=>{const progress=content.querySelector('#batchProgress');if(progress)progress.textContent=(index+1)+' von '+files.length+': '+message}))}catch(error){errors.push({file,error})}const progress=content.querySelector('#batchProgress');if(progress)progress.textContent=(index+1)+' von '+files.length+' Belegen gepr?ft'}
 if(!receipts.length){open('<div class="sheet-title"><h2>Import nicht moeglich</h2><button class="close">&times;</button></div><div class="review-box"><strong>Keine Kassenbons erkannt</strong><p>Bank-Umsatzlisten k?nnen nicht ?ber den Belegstapel importiert werden. Verwende daf?r am Monatsende den PDF-Kontoauszug.</p></div>');return}
 const rows=receipts.map(receipt=>'<div class="detail-row"><span>'+escapeHtml(receipt.name)+'<br><small>'+new Date(receipt.date).toLocaleDateString('de-DE')+'</small></span><strong>? '+euro.format(receipt.amount)+'</strong></div>').join('');
 open('<div class="sheet-title"><h2>Belege erkannt</h2><button class="close">&times;</button></div><p class="subtitle">'+receipts.length+' von '+files.length+' Belegen wurden sicher erkannt.</p><div class="detail-list">'+rows+'</div>'+(errors.length?'<div class="review-box"><strong>'+errors.length+' nicht erkannt</strong><p>Diese Dateien werden nicht uebernommen.</p></div>':'')+'<button class="primary" id="importReceiptBatch">Alle '+receipts.length+' Belege ?bernehmen</button>');
 content.querySelector('#importReceiptBatch').onclick=()=>{for(const receipt of receipts)importReceiptIntoState(receipt);save();sheet.close();render();showToast(receipts.length+' Belege uebernommen')};
}
function importReceiptIntoState(receipt){
 const candidates=transactionCandidates(receipt,item=>String(item.source||'').includes('Kontoauszug'));
 const matching=candidates.filter(item=>sameTransactionMerchant(item.name,receipt.name)||isGenericBankMerchant(item.name));
 if(matching.length===1){const bank=matching[0],bankDate=bank.bankDate||bank.date;Object.assign(bank,receipt,{id:bank.id,date:receipt.date,bankDate,valueDate:bank.valueDate||bankDate,method:bank.method||receipt.method,status:'confirmed',source:'Kontoauszug + Kassenbon',note:bankDateNote(bank.type,bankDate)});delete bank.matchId;return}
 if(candidates.length===1){receipt.status='review';receipt.matchId=candidates[0].id;candidates[0].status='review';candidates[0].matchId=receipt.id}
 state.transactions.push(receipt);
}
function importReceiptTransaction(receipt){
 const candidates=transactionCandidates(receipt,item=>String(item.source||'').includes('Kontoauszug')||String(item.source||'').includes('Konto-Screenshot'));
 const matching=candidates.filter(item=>sameTransactionMerchant(item.name,receipt.name)||isGenericBankMerchant(item.name));
 if(matching.length===1){
  const bank=matching[0],bankDate=bank.bankDate||bank.date,fromScreenshot=String(bank.source||'').includes('Konto-Screenshot');
  Object.assign(bank,receipt,{id:bank.id,date:receipt.date,bankDate,valueDate:bank.valueDate||bankDate,method:bank.method||receipt.method,status:'confirmed',source:(fromScreenshot?'Konto-Screenshot':'Kontoauszug')+' + Kassenbon',note:bankDateNote(bank.type,bankDate)});delete bank.matchId;
  save();sheet.close();render();showToast('Beleg mit Kontoauszug abgeglichen');return;
 }
 if(candidates.length===1){receipt.status='review';receipt.matchId=candidates[0].id;candidates[0].status='review';candidates[0].matchId=receipt.id}
 state.transactions.push(receipt);save();sheet.close();render();showToast(candidates.length===1?'Mögliche Doppelbuchung zur Prüfung':'Beleg übernommen');
}
