(function(){
 const day=86400000,cents=value=>Math.round(Number(value||0)*100),date=value=>new Date(value).getTime(),key=value=>String(value||'').toLowerCase().replace(/gmbh|markt|filiale|[^a-z0-9äöüß]/g,'');
 function merchantMatch(a,b){const left=key(a),right=key(b);return left.length>2&&right.length>2&&(left.includes(right)||right.includes(left))}
 function duplicateMatch(incoming,existing){if(incoming.type!==existing.type||cents(incoming.amount)!==cents(existing.amount))return false;const bookingDistance=Math.abs(date(incoming.date)-date(existing.date)),valueDistance=Math.abs(date(incoming.valueDate||incoming.date)-date(existing.valueDate||existing.date));return Math.min(bookingDistance,valueDistance)<=3*day&&merchantMatch(incoming.name,existing.name)}
 function analyze(result,existing,accountId,movements){const entries=result.transactions.map(transaction=>{const duplicates=existing.filter(item=>duplicateMatch(transaction,item));if(duplicates.length)return {transaction,status:'existing',matchId:duplicates[0].id};const transfers=transaction.type==='expense'&&accountId?movements?.findTransferCandidates(transaction,accountId,3)||[]:[];if(transfers.length===1)return {transaction,status:transfers[0].matchConfidence==='high'?'transfer':'review',transferId:transfers[0].id};if(transfers.length>1)return {transaction,status:'review'};return {transaction,status:'new'}});const counts=entries.reduce((sum,item)=>(sum[item.status]=(sum[item.status]||0)+1,sum),{new:0,existing:0,transfer:0,review:0});return {...result,accountId,entries,counts,importable:counts.new+counts.transfer+counts.review}}
 function commit(plan){const batchId=crypto.randomUUID(),importedAt=new Date().toISOString(),transactions=plan.entries.filter(item=>item.status!=='existing').map(item=>({...item.transaction,accountId:plan.accountId,importBatchId:batchId,importedAt,importStatus:item.status,linkedTransferId:item.status==='transfer'?item.transferId:null,status:item.status==='review'?'review':'confirmed'}));return {batchId,importedAt,transactions,count:transactions.length,statementBalance:plan.balance??null,statementDate:plan.balanceDate||null,accountId:plan.accountId}}
 function batches(transactions){const map=new Map();transactions.filter(item=>item.importBatchId).forEach(item=>{if(!map.has(item.importBatchId))map.set(item.importBatchId,{id:item.importBatchId,importedAt:item.importedAt,accountId:item.accountId,count:0,transactionIds:[]});const batch=map.get(item.importBatchId);batch.count++;batch.transactionIds.push(item.id)});return [...map.values()].sort((a,b)=>date(b.importedAt)-date(a.importedAt))}
 function removeBatch(transactions,batchId){const removed=transactions.filter(item=>item.importBatchId===batchId);return {transactions:transactions.filter(item=>item.importBatchId!==batchId),removed}}
 window.MoneybrainBankImport={analyze,commit,batches,removeBatch,duplicateMatch};
})();
