(function(){
 const categoriesKey='moneybrain.categories.v2',rulesKey='moneybrain.merchantRules.v2',deletedKey='moneybrain.categoryDeleted.v2',now=()=>new Date().toISOString(),slug=value=>String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
 const defaults=[['lebensmittel','Lebensmittel',['Supermarkt','Bäcker','Getränke']],['essen-trinken','Essen & Trinken',['Restaurant','Fast Food','Lieferdienst']],['wohnen','Wohnen',['Miete','Strom','Nebenkosten']],['kommunikation','Kommunikation',['Internet','Mobilfunk']],['mobilitaet','Mobilität',['Tanken','ÖPNV','Auto','Parken']],['versicherungen','Versicherungen',['Krankenversicherung','Haftpflicht','Rechtsschutz']],['familie','Familie',[]],['freizeit','Freizeit',[]],['shopping','Shopping',[]],['gesundheit','Gesundheit',['Apotheke','Arzt']],['abos-dienste','Abos & Dienste',['Streaming','Software']],['gebuehren','Gebühren',[]],['sonstiges','Sonstiges',[]]].map(([id,name,subcategories],index)=>({id,name,subcategories,builtIn:true,sortOrder:(index+1)*10,createdAt:now(),updatedAt:now()}));
 const starterRules=[['rewe','lebensmittel','Supermarkt'],['lidl','lebensmittel','Supermarkt'],['aldi','lebensmittel','Supermarkt'],['netto','lebensmittel','Supermarkt'],['mcdonalds','essen-trinken','Fast Food'],['mvg','mobilitaet','ÖPNV']];
 function load(key,fallback){try{const value=JSON.parse(localStorage.getItem(key)||'null');if(Array.isArray(value))return value}catch{}return fallback}
 let categories=load(categoriesKey,defaults),rules=load(rulesKey,starterRules.map(([merchantKey,categoryId,subcategory])=>({id:crypto.randomUUID(),merchantKey,categoryId,subcategory,createdAt:now(),updatedAt:now()}))),deleted=new Set(load(deletedKey,[]));
 function snapshot(){return {categories:all(),rules:rules.map(item=>({...item}))}}
 function persist(queue=true){localStorage.setItem(categoriesKey,JSON.stringify(categories));localStorage.setItem(rulesKey,JSON.stringify(rules));localStorage.setItem(deletedKey,JSON.stringify([...deleted]));if(queue)window.MoneybrainCloud?.queueCategories(snapshot());window.render?.()}
 function all(){return categories.map(item=>({...item,subcategories:[...item.subcategories]})).sort((a,b)=>a.sortOrder-b.sortOrder)}
 function merchantKey(value){return slug(String(value||'').replace(/gmbh|ohg|ag|ltd|markt|filiale/gi,' '))}
 function ruleFor(name){const key=merchantKey(name);return rules.find(rule=>key===rule.merchantKey||key.includes(rule.merchantKey)||rule.merchantKey.includes(key))||null}
 function apply(transaction){if(transaction.categoryId)return transaction;const rule=ruleFor(transaction.name);return rule?{...transaction,categoryId:rule.categoryId,subcategory:rule.subcategory,categorySource:'merchant-rule'}:transaction}
 function setRule(name,categoryId,subcategory=''){const key=merchantKey(name);if(!key)throw new Error('Händlername fehlt');const existing=rules.find(rule=>rule.merchantKey===key),data={merchantKey:key,categoryId,subcategory,updatedAt:now()};if(existing)Object.assign(existing,data);else rules.push({id:crypto.randomUUID(),createdAt:now(),...data});persist();return data}
 function create(name,subcategories=[]){const clean=String(name||'').trim();if(!clean)throw new Error('Kategoriename fehlt');let id=slug(clean)||crypto.randomUUID();if(categories.some(item=>item.id===id))id+='-'+Date.now();const item={id,name:clean,subcategories:subcategories.map(String).map(value=>value.trim()).filter(Boolean),builtIn:false,sortOrder:Math.max(0,...categories.map(item=>item.sortOrder))+10,createdAt:now(),updatedAt:now()};categories.push(item);persist();return item}
 function update(id,input){const category=categories.find(item=>item.id===id);if(!category)throw new Error('Kategorie nicht gefunden');const name=String(input.name||'').trim();if(!name)throw new Error('Kategoriename fehlt');category.name=name;category.subcategories=(input.subcategories||[]).map(String).map(value=>value.trim()).filter(Boolean);category.updatedAt=now();persist();return {...category}}
 function remove(id,transactions=[]){const category=categories.find(item=>item.id===id);if(!category)throw new Error('Kategorie nicht gefunden');if(transactions.some(item=>item.categoryId===id))throw new Error('Verwendete Kategorien können nicht gelöscht werden. Ordne die betroffenen Einträge zuerst neu zu.');categories=categories.filter(item=>item.id!==id);rules=rules.filter(rule=>rule.categoryId!==id);deleted.add(String(id));persist(false);window.MoneybrainCloud?.deleteCategory(id);window.render?.()}
 function confirmDeleted(id){deleted.delete(String(id));persist(false)}
 function label(categoryId,subcategory=''){const category=categories.find(item=>item.id===categoryId);return category?category.name+(subcategory?' · '+subcategory:''):'Nicht kategorisiert'}
 function applyCloud(categoryRows,ruleRows){if(Array.isArray(categoryRows)&&categoryRows.length)categories=categoryRows.filter(row=>!deleted.has(String(row.id))).map(row=>({id:row.id,name:row.name,subcategories:Array.isArray(row.subcategories)?row.subcategories:[],builtIn:Boolean(row.is_builtin),sortOrder:Number(row.sort_order),createdAt:row.created_at,updatedAt:row.updated_at}));if(Array.isArray(ruleRows))rules=ruleRows.filter(row=>!deleted.has(String(row.category_id))).map(row=>({id:row.id,merchantKey:row.merchant_key,categoryId:row.category_id,subcategory:row.subcategory||'',createdAt:row.created_at,updatedAt:row.updated_at}));persist(false);deleted.forEach(id=>window.MoneybrainCloud?.deleteCategory(id))}
 function exportRows(){return {categories:categories.map(item=>({id:item.id,name:item.name,subcategories:item.subcategories,is_builtin:item.builtIn,sort_order:item.sortOrder,created_at:item.createdAt,updated_at:item.updatedAt})),rules:rules.map(item=>({id:item.id,merchant_key:item.merchantKey,category_id:item.categoryId,subcategory:item.subcategory,created_at:item.createdAt,updated_at:item.updatedAt}))}}
 window.MoneybrainCategories={all,apply,setRule,ruleFor,create,update,remove,confirmDeleted,label,merchantKey,snapshot,applyCloud,exportRows,rules:()=>rules.map(item=>({...item}))};
})();
