(function(){
 const config=window.MONEYBRAIN_SUPABASE||{};
 const sessionKey='moneybrain.supabase.session';
 let session=null,uploadTimer=null,syncing=false;

 function configured(){return /^https:\/\/.+\.supabase\.co$/i.test(config.url||'')&&!String(config.publishableKey||'').startsWith('HIER_')}
 function headers(accessToken,extra={}){return {apikey:config.publishableKey,Authorization:`Bearer ${accessToken||config.publishableKey}`,...extra}}
 function readSession(){try{return JSON.parse(localStorage.getItem(sessionKey)||'null')}catch{return null}}
 function storeSession(value){session=value;if(value)localStorage.setItem(sessionKey,JSON.stringify(value));else localStorage.removeItem(sessionKey)}
 function expiresSoon(value){return !value?.access_token||Number(value.expires_at||0)*1000<Date.now()+60000}
 async function request(path,options={}){const response=await fetch(config.url+path,options);const text=await response.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!response.ok)throw new Error(body?.msg||body?.message||body?.error_description||'Cloud-Anfrage fehlgeschlagen');return body}
 async function refresh(){if(!session?.refresh_token)return null;try{const next=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:headers(null,{'Content-Type':'application/json'}),body:JSON.stringify({refresh_token:session.refresh_token})});next.expires_at=Math.floor(Date.now()/1000)+Number(next.expires_in||3600);storeSession(next);return next}catch{storeSession(null);return null}}
 async function validSession(){session=readSession();if(session&&expiresSoon(session))await refresh();return session}
 async function login(email,password){const next=await request('/auth/v1/token?grant_type=password',{method:'POST',headers:headers(null,{'Content-Type':'application/json'}),body:JSON.stringify({email,password})});next.expires_at=Math.floor(Date.now()/1000)+Number(next.expires_in||3600);storeSession(next);return next}
 async function cloudRow(){const rows=await request('/rest/v1/moneybrain_data?select=transactions,updated_at',{headers:headers(session.access_token)});return Array.isArray(rows)?rows[0]:null}
 async function upload(items){if(!session||syncing)return;syncing=true;try{const updatedAt=localStorage.getItem('moneybrain.localUpdatedAt')||new Date().toISOString();await request('/rest/v1/moneybrain_data?on_conflict=user_id',{method:'POST',headers:headers(session.access_token,{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'}),body:JSON.stringify({user_id:session.user.id,transactions:items,updated_at:updatedAt})});setCloudStatus('Gesichert')}catch(error){setCloudStatus('Nicht synchronisiert');console.error(error)}finally{syncing=false}}
 function queueUpload(items){if(!configured()||!session)return;clearTimeout(uploadTimer);uploadTimer=setTimeout(()=>upload(items),500)}
 async function synchronize(){const row=await cloudRow(),local=window.moneybrainGetTransactions(),localStamp=Date.parse(localStorage.getItem('moneybrain.localUpdatedAt')||'')||0,cloudStamp=Date.parse(row?.updated_at||'')||0;if(!row){await upload(local);return}const cloud=Array.isArray(row.transactions)?row.transactions:[];if(cloud.length&&(!local.length||cloudStamp>localStamp)){window.moneybrainApplyCloudTransactions(cloud,row.updated_at);setCloudStatus('Wiederhergestellt');return}if(localStamp>cloudStamp)await upload(local);else setCloudStatus('Synchronisiert')}
 function setCloudStatus(text){const el=document.querySelector('#cloudStatus');if(el)el.textContent=text}
 function showLogin(message=''){const overlay=document.querySelector('#authOverlay');if(!overlay)return;overlay.hidden=false;document.querySelector('.app-shell').setAttribute('aria-hidden','true');const error=document.querySelector('#authError');error.textContent=message;document.querySelector('#loginForm').onsubmit=async event=>{event.preventDefault();const button=event.submitter||event.currentTarget.querySelector('button[type="submit"]');error.textContent='';button.disabled=true;try{const form=new FormData(event.currentTarget);await login(String(form.get('email')).trim(),String(form.get('password')));overlay.hidden=true;document.querySelector('.app-shell').removeAttribute('aria-hidden');await synchronize();window.render?.()}catch(e){error.textContent='Anmeldung nicht möglich. Bitte E-Mail und Passwort prüfen.'}finally{button.disabled=false}}}
 async function init(){if(!configured())return {configured:false};if(!await validSession()){showLogin();return {configured:true,authenticated:false}}try{await synchronize();return {configured:true,authenticated:true}}catch(error){showLogin('Cloud-Verbindung fehlgeschlagen. Bitte erneut anmelden.');return {configured:true,authenticated:false}}}
 async function signOut(){if(session?.access_token){try{await request('/auth/v1/logout',{method:'POST',headers:headers(session.access_token)})}catch{}}storeSession(null);location.reload()}
 window.MoneybrainCloud={init,queueUpload,signOut,isConfigured:configured,isSignedIn:()=>Boolean(session)};
})();
