(function(){
 const storageKey='moneybrain.fixedCosts.v2',ignoredKey='moneybrain.fixedCostIgnored.v2',now=()=>new Date().toISOString(),num=value=>Math.round((Number(value||0)+Number.EPSILON)*100)/100;
 const rhythms={monthly:{label:'Monatlich',months:1},quarterly:{label:'Vierteljährlich',months:3},semiannual:{label:'Halbjährlich',months:6},annual:{label:'Jährlich',months:12},custom:{label:'Benutzerdefiniert',months:1}};
 function load(key,fallback=[]){try{const value=JSON.parse(localStorage.getItem(key)||'null');return Array.isArray(value)?value:fallback}catch{return fallback}}
 function normalize(item){const expected=num(item.expectedAmount),history=Array.isArray(item.amountHistory)?item.amountHistory:[];return {id:String(item.id||crypto.randomUUID()),name:String(item.name||'Fixkosten').trim(),categoryId:String(item.categoryId||''),subcategory:String(item.subcategory||''),amountType:item.amountType==='variable'?'variable':'fixed',expectedAmount:expected,rhythm:rhythms[item.rhythm]?item.rhythm:'monthly',customMonths:Math.max(1,Number(item.customMonths||1)),dueDay:Math.min(31,Math.max(1,Number(item.dueDay||1))),accountId:String(item.accountId||''),nextDue:String(item.nextDue||new Date().toISOString().slice(0,10)),active:item.active!==false,autoMatch:item.autoMatch!==false,merchantKey:String(item.merchantKey||merchantKey(item.name)),amountHistory:history.length?history.map(entry=>({amount:num(entry.amount),validFrom:entry.validFrom||now(),source:entry.source||'manual'})):[{amount:expected,validFrom:item.createdAt||now(),source:'manual'}],paymentHistory:Array.isArray(item.paymentHistory)?item.paymentHistory.map(entry=>({...entry})):[],createdAt:item.createdAt||now(),updatedAt:item.updatedAt||now()}}
 let items=load(storageKey).map(normalize),ignored=new Set(load(ignoredKey));
 function merchantKey(value){return String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\.com\b|gmbh|ohg|\bag\b|ltd|limited|[^a-z0-9]/g,'')}
 function persist(queue=true){localStorage.setItem(storageKey,JSON.stringify(items));localStorage.setItem(ignoredKey,JSON.stringify([...ignored]));if(queue)window.MoneybrainCloud?.queueFixedCosts(snapshot());window.render?.()}
 function all(){return items.map(item=>structuredClone(item)).sort((a,b)=>a.nextDue.localeCompare(b.nextDue)||a.name.localeCompare(b.name))}
 function planningAmount(item){return item.amountType==='variable'?Math.max(item.expectedAmount,...item.amountHistory.map(entry=>num(entry.amount))):item.expectedAmount}
 function monthsFor(item){return item.rhythm==='custom'?item.customMonths:rhythms[item.rhythm].months}
 function occurrenceInMonth(item,year,month){const first=new Date(item.nextDue+'T12:00:00');if(Number.isNaN(first.getTime()))return null;const start=first.getFullYear()*12+first.getMonth(),target=year*12+month,difference=target-start;if(difference<0||difference%monthsFor(item)!==0)return null;const lastDay=new Date(year,month+1,0).getDate();return new Date(year,month,Math.min(item.dueDay,lastDay),12)}
 function matchingTransaction(item,due,transactions){if(!item.autoMatch)return null;const amount=planningAmount(item),range=item.amountType==='variable'?Math.max(1,amount*.35):Math.max(.02,amount*.03);return transactions.filter(tx=>tx.type==='expense'&&!tx.amountUncertain&&(!item.accountId||tx.accountId===item.accountId)&&Math.abs(new Date(tx.date)-due)<=7*86400000&&Math.abs(Number(tx.amount)-amount)<=range&&(()=>{const key=merchantKey(tx.name);return key.includes(item.merchantKey)||item.merchantKey.includes(key)})()).sort((a,b)=>Math.abs(Number(a.amount)-amount)-Math.abs(Number(b.amount)-amount))[0]||null}
 function month(year=new Date().getFullYear(),monthIndex=new Date().getMonth(),transactions=[]){const claimed=new Set(),rows=items.filter(item=>item.active).map(item=>{const due=occurrenceInMonth(item,year,monthIndex);if(!due)return null;const occurrence=due.toISOString().slice(0,7),manual=item.paymentHistory.find(entry=>entry.occurrence===occurrence),transaction=manual?.paid?null:matchingTransaction(item,due,transactions.filter(tx=>!claimed.has(tx.id)));if(transaction)claimed.add(transaction.id);const expected=planningAmount(item),paid=manual?Boolean(manual.paid):Boolean(transaction),actual=manual?.paid?num(manual.amount||expected):(transaction?Number(transaction.amount):0);return {...structuredClone(item),due:due.toISOString(),occurrence,expected,transaction,paid,manualPaid:Boolean(manual?.paid),actual}}).filter(Boolean);return {rows,expected:num(rows.reduce((sum,row)=>sum+row.expected,0)),paid:num(rows.reduce((sum,row)=>sum+(row.paid?row.actual:0),0)),open:num(rows.reduce((sum,row)=>sum+(row.paid?0:row.expected),0))}}
 function save(input,id=null){const existing=items.find(item=>item.id===id),data=normalize({...existing,...input,id:id||crypto.randomUUID(),createdAt:existing?.createdAt||now(),updatedAt:now()});if(existing&&num(existing.expectedAmount)!==num(data.expectedAmount))data.amountHistory=[...existing.amountHistory,{amount:data.expectedAmount,validFrom:now(),source:'manual'}];if(existing)items[items.indexOf(existing)]=data;else items.push(data);persist();return structuredClone(data)}
 function remove(id){items=items.filter(item=>item.id!==id);persist()}
 function setPaid(id,occurrence,paid,amount){const item=items.find(entry=>entry.id===id);if(!item)throw new Error('Fixkosten nicht gefunden');item.paymentHistory=item.paymentHistory.filter(entry=>entry.occurrence!==occurrence);item.paymentHistory.push({occurrence,paid:Boolean(paid),amount:num(amount||item.expectedAmount),updatedAt:now(),source:'manual'});item.updatedAt=now();persist();return structuredClone(item)}
 function candidates(transactions=[]){const groups=new Map();for(const tx of transactions.filter(tx=>tx.type==='expense'&&!tx.amountUncertain)){const key=merchantKey(tx.name);if(key.length<3||ignored.has(key))continue;const group=groups.get(key)||[];group.push(tx);groups.set(key,group)}const result=[];for(const [key,group] of groups){if(group.length<3||items.some(item=>item.merchantKey===key))continue;group.sort((a,b)=>new Date(a.date)-new Date(b.date));const gaps=group.slice(1).map((tx,index)=>(new Date(tx.date)-new Date(group[index].date))/86400000),monthly=gaps.filter(gap=>gap>=24&&gap<=38).length>=2;if(!monthly)continue;const amounts=group.map(tx=>num(tx.amount)),variable=Math.max(...amounts)-Math.min(...amounts)>.02;result.push({key,name:group.at(-1).name,count:group.length,amountType:variable?'variable':'fixed',expectedAmount:variable?Math.max(...amounts):amounts.at(-1),dueDay:new Date(group.at(-1).date).getDate(),accountId:group.at(-1).accountId||'',amounts})}return result}
 function ignore(key){ignored.add(key);persist()}
 function fromCandidate(candidate){return save({name:candidate.name,merchantKey:candidate.key,amountType:candidate.amountType,expectedAmount:candidate.expectedAmount,rhythm:'monthly',dueDay:candidate.dueDay,accountId:candidate.accountId,nextDue:new Date().toISOString().slice(0,7)+'-'+String(candidate.dueDay).padStart(2,'0'),amountHistory:candidate.amounts.map((amount,index)=>({amount,validFrom:now(),source:'detected-'+index}))})}
 function snapshot(){return {items:all(),ignored:[...ignored]}}
 function exportRows(){return items.map(item=>({id:item.id,name:item.name,category_id:item.categoryId||null,subcategory:item.subcategory,amount_type:item.amountType,expected_amount:item.expectedAmount,rhythm:item.rhythm,custom_months:item.customMonths,due_day:item.dueDay,account_id:item.accountId||null,next_due:item.nextDue,is_active:item.active,auto_match:item.autoMatch,merchant_key:item.merchantKey,amount_history:item.amountHistory,payment_history:item.paymentHistory,created_at:item.createdAt,updated_at:item.updatedAt}))}
 function applyCloud(rows){if(!Array.isArray(rows))return;if(rows.length)items=rows.map(row=>normalize({id:row.id,name:row.name,categoryId:row.category_id,subcategory:row.subcategory,amountType:row.amount_type,expectedAmount:row.expected_amount,rhythm:row.rhythm,customMonths:row.custom_months,dueDay:row.due_day,accountId:row.account_id,nextDue:row.next_due,active:row.is_active,autoMatch:row.auto_match,merchantKey:row.merchant_key,amountHistory:row.amount_history,paymentHistory:row.payment_history,createdAt:row.created_at,updatedAt:row.updated_at}));persist(false)}
 window.MoneybrainFixedCosts={rhythms,all,save,remove,setPaid,month,candidates,ignore,fromCandidate,planningAmount,snapshot,exportRows,applyCloud,merchantKey};
})();
