(function(){
 const key='moneybrain.notifications.v2',sentKey='moneybrain.notifications.sent.v1',defaults={rareCosts:true,rareCostThreshold:100,rareCostDays:[60,30,7,0],underfunding:true,browser:false};
 function normalizeDays(value){const source=Array.isArray(value)?value:defaults.rareCostDays;return [...new Set(source.map(Number).filter(day=>[60,30,7,0].includes(day)))].sort((a,b)=>b-a)}
 function preferences(){try{const stored={...defaults,...JSON.parse(localStorage.getItem(key)||'{}')};stored.rareCostDays=normalizeDays(stored.rareCostDays);stored.rareCostThreshold=Math.max(0,Number(stored.rareCostThreshold??100));return stored}catch{return {...defaults,rareCostDays:[...defaults.rareCostDays]}}}
 function save(input,queue=true){const next={...preferences(),...input};next.rareCostDays=normalizeDays(next.rareCostDays);next.rareCostThreshold=Math.max(0,Number(next.rareCostThreshold??100));localStorage.setItem(key,JSON.stringify(next));if(queue)window.MoneybrainCloud?.queueNotificationPreferences(next);window.render?.();return next}
 function calendarDays(from,to){const start=new Date(from.getFullYear(),from.getMonth(),from.getDate()),end=new Date(to.getFullYear(),to.getMonth(),to.getDate());return Math.round((end-start)/86400000)}
 function alerts(transactions=[],today=new Date()){
  const prefs=preferences(),result=[],seen=new Set(),cashflow=window.MoneybrainCashflow.forecast(transactions,today,120);
  if(prefs.underfunding&&!cashflow.covered){const critical=cashflow.events.find(event=>event.type==='expense'&&event.after<cashflow.safety),days=critical?Math.ceil((new Date(critical.date)-today)/86400000):null;result.push({type:'underfunding',level:days!==null&&days<=1?'critical':days!==null&&days<=7?'warning':'notice',title:'Kommende Verpflichtungen nicht gedeckt',message:critical?`${critical.label}: voraussichtlicher Fehlbetrag ${Math.max(0,cashflow.safety-critical.after).toFixed(2)} €`:'Die Cashflow-Prognose unterschreitet deine Sicherheitsreserve.',date:critical?.date})}
  if(prefs.rareCosts&&prefs.rareCostDays.length){const maxDays=Math.max(...prefs.rareCostDays);for(let offset=0;offset<=Math.ceil(maxDays/28)+1;offset++){const date=new Date(today.getFullYear(),today.getMonth()+offset,1),summary=window.MoneybrainFixedCosts.month(date.getFullYear(),date.getMonth(),transactions);for(const item of summary.rows.filter(item=>!item.paid&&item.expected>prefs.rareCostThreshold&&['quarterly','semiannual','annual','custom'].includes(item.rhythm))){const days=calendarDays(today,new Date(item.due));if(!prefs.rareCostDays.includes(days))continue;const occurrence=`${item.id||item.name}-${String(item.due).slice(0,10)}-${days}`;if(seen.has(occurrence))continue;seen.add(occurrence);result.push({id:item.id,type:'rare-cost',level:days===0?'warning':'notice',title:item.name,message:days===0?`Heute werden voraussichtlich ${item.expected.toFixed(2)} € fällig.`:`In ${days} Tagen werden voraussichtlich ${item.expected.toFixed(2)} € fällig.`,date:item.due,reminderDay:days})}}}
  return result;
 }
 async function enableBrowser(){if(!('Notification'in window))throw new Error('Browser-Benachrichtigungen werden nicht unterstützt');const permission=await Notification.requestPermission();save({browser:permission==='granted'});return permission}
 function notify(alertItems){if(!preferences().browser||Notification.permission!=='granted')return;let sent=[];try{sent=JSON.parse(localStorage.getItem(sentKey)||'[]')}catch{}const known=new Set(Array.isArray(sent)?sent:[]);for(const item of alertItems){const id=`${item.type}-${item.id||''}-${item.date||''}-${item.reminderDay??''}`;if(known.has(id))continue;new Notification(item.title,{body:item.message,tag:`moneybrain-${id}`});known.add(id)}localStorage.setItem(sentKey,JSON.stringify([...known].slice(-200)))}
 function exportRow(){const item=preferences();return {rare_costs:item.rareCosts,underfunding:item.underfunding,browser_notifications:item.browser}}
 function applyCloud(row){if(row)save({rareCosts:row.rare_costs,underfunding:row.underfunding,browser:row.browser_notifications},false)}
 window.MoneybrainNotifications={preferences,save,alerts,enableBrowser,notify,exportRow,applyCloud};
})();
