(function(){
 const key='moneybrain.notifications.v2',defaults={rareCosts:true,underfunding:true,browser:false};
 function preferences(){try{return {...defaults,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return {...defaults}}}
 function save(input,queue=true){const next={...preferences(),...input};localStorage.setItem(key,JSON.stringify(next));if(queue)window.MoneybrainCloud?.queueNotificationPreferences(next);window.render?.();return next}
 function alerts(transactions=[],today=new Date()){const prefs=preferences(),result=[],cashflow=window.MoneybrainCashflow.forecast(transactions,today,120);if(prefs.underfunding&&!cashflow.covered){const critical=cashflow.events.find(event=>event.type==='expense'&&event.after<cashflow.safety),days=critical?Math.ceil((new Date(critical.date)-today)/86400000):null;result.push({type:'underfunding',level:days!==null&&days<=1?'critical':days!==null&&days<=7?'warning':'notice',title:'Kommende Verpflichtungen nicht gedeckt',message:critical?`${critical.label}: voraussichtlicher Fehlbetrag ${Math.max(0,cashflow.safety-critical.after).toFixed(2)} €`:'Die Cashflow-Prognose unterschreitet deine Sicherheitsreserve.',date:critical?.date})}if(prefs.rareCosts){for(let offset=0;offset<=1;offset++){const date=new Date(today.getFullYear(),today.getMonth()+offset,1),summary=window.MoneybrainFixedCosts.month(date.getFullYear(),date.getMonth(),transactions);for(const item of summary.rows.filter(item=>!item.paid&&item.expected>100&&['quarterly','semiannual','annual'].includes(item.rhythm))){const days=Math.ceil((new Date(item.due)-today)/86400000),monthStart=today.getDate()===1&&today.getMonth()===date.getMonth();if(monthStart||days===7)result.push({type:'rare-cost',level:'notice',title:item.name,message:days===7?`In 7 Tagen werden voraussichtlich ${item.expected.toFixed(2)} € fällig.`:`In diesem Monat werden voraussichtlich ${item.expected.toFixed(2)} € fällig.`,date:item.due})}}}return result}
 async function enableBrowser(){if(!('Notification'in window))throw new Error('Browser-Benachrichtigungen werden nicht unterstützt');const permission=await Notification.requestPermission();save({browser:permission==='granted'});return permission}
 function notify(alertItems){if(!preferences().browser||Notification.permission!=='granted')return;alertItems.forEach(item=>new Notification(item.title,{body:item.message,tag:`moneybrain-${item.type}-${item.date||''}`}))}
 function exportRow(){const item=preferences();return {rare_costs:item.rareCosts,underfunding:item.underfunding,browser_notifications:item.browser}}
 function applyCloud(row){if(row)save({rareCosts:row.rare_costs,underfunding:row.underfunding,browser:row.browser_notifications},false)}
 window.MoneybrainNotifications={preferences,save,alerts,enableBrowser,notify,exportRow,applyCloud};
})();
