(function(){
 const storageKey='moneybrain.recurringIncome.v2',ignoredKey='moneybrain.recurringIncomeIgnored.v2',categoryKey='moneybrain.incomeCategories.v2',now=()=>new Date().toISOString(),num=value=>Math.round((Number(value||0)+Number.EPSILON)*100)/100;
 const rhythms={monthly:{label:'Monatlich',months:1},quarterly:{label:'Vierteljährlich',months:3},semiannual:{label:'Halbjährlich',months:6},annual:{label:'Jährlich',months:12},custom:{label:'Benutzerdefiniert',months:1}},defaultCategories=['Rente','Gehalt','Erstattung','Verkauf','Geschenk / Privat','Sonstige Einnahme'];
 function load(key,fallback=[]){try{const value=JSON.parse(localStorage.getItem(key)||'null');return Array.isArray(value)?value:fallback}catch{return fallback}}
 function key(value){return String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\.com\b|gmbh|ohg|\bag\b|ltd|limited|[^a-z0-9]/g,'')}
 function normalize(item){const amount=num(item.expectedAmount);return {id:String(item.id||crypto.randomUUID()),name:String(item.name||'Regelmäßige Einnahme').trim(),senderKey:String(item.senderKey||key(item.name)),expectedAmount:amount,rhythm:rhythms[item.rhythm]?item.rhythm:'monthly',customMonths:Math.max(1,Number(item.customMonths||1)),dueDay:Math.min(31,Math.max(1,Number(item.dueDay||1))),accountId:String(item.accountId||''),nextDue:String(item.nextDue||new Date().toISOString().slice(0,10)),category:String(item.category||'Sonstige Einnahme'),active:item.active!==false,autoMatch:item.autoMatch!==false,amountHistory:Array.isArray(item.amountHistory)&&item.amountHistory.length?item.amountHistory.map(entry=>({amount:num(entry.amount),validFrom:entry.validFrom||now(),source:entry.source||'manual',occurrence:entry.occurrence||null,received:entry.received===undefined?undefined:Boolean(entry.received)})):[{amount,validFrom:item.createdAt||now(),source:'manual'}],createdAt:item.createdAt||now(),updatedAt:item.updatedAt||now()}}
 let items=load(storageKey).map(normalize),ignored=new Set(load(ignoredKey)),categories=load(categoryKey,defaultCategories);
 function persist(queue=true){localStorage.setItem(storageKey,JSON.stringify(items));localStorage.setItem(ignoredKey,JSON.stringify([...ignored]));localStorage.setItem(categoryKey,JSON.stringify(categories));if(queue)window.MoneybrainCloud?.queueRecurringIncome(snapshot());window.render?.()}
 function all(){return items.map(item=>structuredClone(item)).sort((a,b)=>a.nextDue.localeCompare(b.nextDue)||a.name.localeCompare(b.name))}
 function monthsFor(item){return item.rhythm==='custom'?item.customMonths:rhythms[item.rhythm].months}
 function occurrenceInMonth(item,year,month){const first=new Date(item.nextDue+'T12:00:00');if(Number.isNaN(first.getTime()))return null;const difference=year*12+month-(first.getFullYear()*12+first.getMonth());if(difference<0||difference%monthsFor(item)!==0)return null;return new Date(year,month,Math.min(item.dueDay,new Date(year,month+1,0).getDate()),12)}
 function matching(item,due,transactions){if(!item.autoMatch)return null;return transactions.filter(tx=>tx.type==='income'&&!tx.amountUncertain&&(!item.accountId||tx.accountId===item.accountId)&&Math.abs(new Date(tx.date)-due)<=7*86400000&&Math.abs(Number(tx.amount)-item.expectedAmount)<=Math.max(.02,item.expectedAmount*.08)&&(()=>{const txKey=key(tx.name);return txKey.includes(item.senderKey)||item.senderKey.includes(txKey)})()).sort((a,b)=>Math.abs(Number(a.amount)-item.expectedAmount)-Math.abs(Number(b.amount)-item.expectedAmount))[0]||null}
 function month(year,monthIndex,transactions=[]){return items.filter(item=>item.active).map(item=>{const due=occurrenceInMonth(item,year,monthIndex);if(!due)return null;const occurrence=due.toISOString().slice(0,7),manual=[...item.amountHistory].reverse().find(entry=>entry.source==='manual-received'&&entry.occurrence===occurrence),transaction=manual?null:matching(item,due,transactions),received=manual?Boolean(manual.received):Boolean(transaction),actual=manual?.received?num(manual.amount||item.expectedAmount):(transaction?Number(transaction.amount):0);return {...structuredClone(item),due:due.toISOString(),occurrence,transaction,manualReceived:manual?Boolean(manual.received):null,received,actual}}).filter(Boolean)}
 function save(input,id=null){const existing=items.find(item=>item.id===id),data=normalize({...existing,...input,id:id||crypto.randomUUID(),createdAt:existing?.createdAt||now(),updatedAt:now()});if(existing&&num(existing.expectedAmount)!==data.expectedAmount)data.amountHistory=[...existing.amountHistory,{amount:data.expectedAmount,validFrom:now(),source:'manual'}];if(existing)items[items.indexOf(existing)]=data;else items.push(data);persist();return structuredClone(data)}
 function remove(id){items=items.filter(item=>item.id!==id);persist()}
 function setReceived(id,occurrence,received,amount){const item=items.find(entry=>entry.id===id);if(!item)throw new Error('Regelmäßige Einnahme nicht gefunden');item.amountHistory=item.amountHistory.filter(entry=>!(entry.source==='manual-received'&&entry.occurrence===occurrence));item.amountHistory.push({amount:num(amount||item.expectedAmount),validFrom:now(),source:'manual-received',occurrence,received:Boolean(received)});item.updatedAt=now();persist();return structuredClone(item)}
 function candidates(transactions=[]){const groups=new Map();for(const tx of transactions.filter(tx=>tx.type==='income'&&!tx.amountUncertain)){const senderKey=key(tx.name);if(senderKey.length<3||ignored.has(senderKey))continue;const group=groups.get(senderKey)||[];group.push(tx);groups.set(senderKey,group)}const result=[];for(const [senderKey,group] of groups){if(group.length<3||items.some(item=>item.senderKey===senderKey))continue;group.sort((a,b)=>new Date(a.date)-new Date(b.date));const gaps=group.slice(1).map((tx,index)=>(new Date(tx.date)-new Date(group[index].date))/86400000);if(gaps.filter(gap=>gap>=24&&gap<=38).length<2)continue;const amounts=group.map(tx=>num(tx.amount));result.push({senderKey,name:group.at(-1).name,count:group.length,expectedAmount:amounts.at(-1),dueDay:new Date(group.at(-1).date).getDate(),accountId:group.at(-1).accountId||'',amounts})}return result}
 function fromCandidate(candidate){return save({name:candidate.name,senderKey:candidate.senderKey,expectedAmount:candidate.expectedAmount,rhythm:'monthly',dueDay:candidate.dueDay,accountId:candidate.accountId,nextDue:new Date().toISOString().slice(0,7)+'-'+String(candidate.dueDay).padStart(2,'0'),amountHistory:candidate.amounts.map(amount=>({amount,validFrom:now(),source:'detected'}))})}
 function ignore(senderKey){ignored.add(senderKey);persist()}
 function addCategory(name){const clean=String(name||'').trim();if(clean&&!categories.some(item=>item.toLowerCase()===clean.toLowerCase())){categories.push(clean);persist()}return [...categories]}
 function snapshot(){return {items:all(),ignored:[...ignored],categories:[...categories]}}
 function exportRows(){return items.map(item=>({id:item.id,name:item.name,sender_key:item.senderKey,expected_amount:item.expectedAmount,rhythm:item.rhythm,custom_months:item.customMonths,due_day:item.dueDay,account_id:item.accountId||null,next_due:item.nextDue,category:item.category,is_active:item.active,auto_match:item.autoMatch,amount_history:item.amountHistory,created_at:item.createdAt,updated_at:item.updatedAt}))}
 function applyCloud(rows){if(Array.isArray(rows)&&rows.length){items=rows.map(row=>normalize({id:row.id,name:row.name,senderKey:row.sender_key,expectedAmount:row.expected_amount,rhythm:row.rhythm,customMonths:row.custom_months,dueDay:row.due_day,accountId:row.account_id,nextDue:row.next_due,category:row.category,active:row.is_active,autoMatch:row.auto_match,amountHistory:row.amount_history,createdAt:row.created_at,updatedAt:row.updated_at}));persist(false)}}
 window.MoneybrainRecurringIncome={rhythms,all,month,save,remove,setReceived,candidates,fromCandidate,ignore,categories:()=>[...categories],addCategory,snapshot,exportRows,applyCloud,key};
})();
